In [1]:
from nba_api.stats.endpoints import leaguegamelog
import json

In [2]:
extract = leaguegamelog.LeagueGameLog(
        player_or_team_abbreviation='P', # 'P' for Player stats
        season='2025-26',
        season_type_all_star='Regular Season'
    )

In [10]:
extract_json = extract.get_json()
extract_normalized_json = extract.get_normalized_json()
extract_df = extract.get_data_frames()[0]

In [12]:
cog = json.loads(extract_json)
cog2 = json.loads(extract_normalized_json)

In [16]:
cog2['LeagueGameLog']

[{'SEASON_ID': '22025',
  'PLAYER_ID': 1642964,
  'PLAYER_NAME': 'Brooks Barnhizer',
  'TEAM_ID': 1610612760,
  'TEAM_ABBREVIATION': 'OKC',
  'TEAM_NAME': 'Oklahoma City Thunder',
  'GAME_ID': '0022500001',
  'GAME_DATE': '2025-10-21',
  'MATCHUP': 'OKC vs. HOU',
  'WL': 'W',
  'MIN': 2,
  'FGM': 0,
  'FGA': 0,
  'FG_PCT': None,
  'FG3M': 0,
  'FG3A': 0,
  'FG3_PCT': None,
  'FTM': 0,
  'FTA': 0,
  'FT_PCT': None,
  'OREB': 0,
  'DREB': 0,
  'REB': 0,
  'AST': 0,
  'STL': 0,
  'BLK': 0,
  'TOV': 0,
  'PF': 0,
  'PTS': 0,
  'PLUS_MINUS': -2,
  'FANTASY_PTS': 0.0,
  'VIDEO_AVAILABLE': 1},
 {'SEASON_ID': '22025',
  'PLAYER_ID': 1642959,
  'PLAYER_NAME': 'Chris Youngblood',
  'TEAM_ID': 1610612760,
  'TEAM_ABBREVIATION': 'OKC',
  'TEAM_NAME': 'Oklahoma City Thunder',
  'GAME_ID': '0022500001',
  'GAME_DATE': '2025-10-21',
  'MATCHUP': 'OKC vs. HOU',
  'WL': 'W',
  'MIN': 0,
  'FGM': 0,
  'FGA': 0,
  'FG_PCT': None,
  'FG3M': 0,
  'FG3A': 0,
  'FG3_PCT': None,
  'FTM': 0,
  'FTA': 0,
  'FT_PCT': None,
  'OREB': 0,
  'DREB': 0,
  'REB': 0,
  'AST': 0,
  'STL': 0,
  'BLK': 0,
  'TOV': 0,
  'PF': 0,
  'PTS': 0,
  'PLUS_MINUS': 0,
  'FANTASY_PTS': 0.0,
  'VIDEO_AVAILABLE': 1},
 {'SEASON_ID': '22025',
  'PLAYER_ID': 1641717,
  'PLAYER_NAME': 'Cason Wallace',
  'TEAM_ID': 1610612760,
  'TEAM_ABBREVIATION': 'OKC',
  'TEAM_NAME': 'Oklahoma City Thunder',
  'GAME_ID': '0022500001',
  'GAME_DATE': '2025-10-21',
  'MATCHUP': 'OKC vs. HOU',
  'WL': 'W',
  'MIN': 42,
  'FGM': 5,
  'FGA': 10,
  'FG_PCT': 0.5,
  'FG3M': 3,
  'FG3A': 8,
  'FG3_PCT': 0.375,
  'FTM': 1,
  'FTA': 2,
  'FT_PCT': 0.5,
  'OREB': 1,
  'DREB': 6,
  'REB': 7,
  'AST': 5,
  'STL': 4,
  'BLK': 0,
  'TOV': 2,
  'PF': 3,
  'PTS': 14,
  'PLUS_MINUS': 8,
  'FANTASY_PTS': 39.9,
  'VIDEO_AVAILABLE': 1},
 {'SEASON_ID': '22025',
  'PLAYER_ID': 1631119,
  'PLAYER_NAME': 'Jaylin Williams',
  'TEAM_ID': 1610612760,
  'TEAM_ABBREVIATION': 'OKC',
  'TEAM_NAME': 'Oklahoma City Thunder',
  'GAME_ID': '0022500001',
  'GAME_DATE': '2025-10-21',
  'MATCHUP': 'OKC vs. HOU',
  'WL': 'W',
  'MIN': 13,
  'FGM': 1,
  'FGA': 5,
  'FG_PCT': 0.2,
  'FG3M': 0,
  'FG3A': 4,
  'FG3_PCT': 0.0,
  'FTM': 0,
  'FTA': 0,
  'FT_PCT': None,
  'OREB': 0,
  'DREB': 0,
  'REB': 0,
  'AST': 1,
  'STL': 1,
  'BLK': 0,
  'TOV': 0,
  'PF': 1,
  'PTS': 2,
  'PLUS_MINUS': -3,
  'FANTASY_PTS': 6.5,
  'VIDEO_AVAILABLE': 1},
 {'SEASON_ID': '22025',
  'PLAYER_ID': 1631096,
  'PLAYER_NAME': 'Chet Holmgren',
  'TEAM_ID': 1610612760,
  'TEAM_ABBREVIATION': 'OKC',
  'TEAM_NAME': 'Oklahoma City Thunder',
  'GAME_ID': '0022500001',
  'GAME_DATE': '2025-10-21',
  'MATCHUP': 'OKC vs. HOU',
  'WL': 'W',
  'MIN': 38,
  'FGM': 11,
  'FGA': 17,
  'FG_PCT': 0.647,
  'FG3M': 2,
  'FG3A': 5,
  'FG3_PCT': 0.4,
  'FTM': 4,
  'FTA': 4,
  'FT_PCT': 1.0,
  'OREB': 2,
  'DREB': 5,
  'REB': 7,
  'AST': 2,
  'STL': 0,
  'BLK': 0,
  'TOV': 3,
  'PF': 6,
  'PTS': 28,
  'PLUS_MINUS': -1,
  'FANTASY_PTS': 36.4,
  'VIDEO_AVAILABLE': 1},
 {'SEASON_ID': '22025',
  'PLAYER_ID': 1630598,
  'PLAYER_NAME': 'Aaron Wiggins',
  'TEAM_ID': 1610612760,
  'TEAM_ABBREVIATION': 'OKC',
  'TEAM_NAME': 'Oklahoma City Thunder',
  'GAME_ID': '0022500001',
  'GAME_DATE': '2025-10-21',
  'MATCHUP': 'OKC vs. HOU',
  'WL': 'W',
  'MIN': 21,
  'FGM': 4,
  'FGA': 8,
  'FG_PCT': 0.5,
  'FG3M': 2,
  'FG3A': 5,
  'FG3_PCT': 0.4,
  'FTM': 0,
  'FTA': 0,
  'FT_PCT': None,
  'OREB': 0,
  'DREB': 1,
  'REB': 1,
  'AST': 1,
  'STL': 0,
  'BLK': 0,
  'TOV': 1,
  'PF': 1,
  'PTS': 10,
  'PLUS_MINUS': 2,
  'FANTASY_PTS': 11.7,
  'VIDEO_AVAILABLE': 1},
 {'SEASON_ID': '22025',
  'PLAYER_ID': 1629652,
  'PLAYER_NAME': 'Luguentz Dort',
  'TEAM_ID': 1610612760,
  'TEAM_ABBREVIATION': 'OKC',
  'TEAM_NAME': 'Oklahoma City Thunder',
  'GAME_ID': '0022500001',
  'GAME_DATE': '2025-10-21',
  'MATCHUP': 'OKC vs. HOU',
  'WL': 'W',
  'MIN': 45,
  'FGM': 2,
  'FGA': 12,
  'FG_PCT': 0.167,
  'FG3M': 0,
  'FG3A': 8,
  'FG3_PCT': 0.0,
  'FTM': 2,
  'FTA': 2,
  'FT_PCT': 1.0,
  'OREB': 2,
  'DREB': 4,
  'REB': 6,
  'AST': 5,
  'STL': 1,
  'BLK': 0,
  'TOV': 1,
  'PF': 4,
  'PTS': 6,
  'PLUS_MINUS': 2,
  'FANTASY_PTS': 22.7,
  'VIDEO_AVAILABLE': 1},
 {'SEASON_ID': '22025',
  'PLAYER_ID': 1628983,
  'PLAYER_NAME': 'Shai Gilgeous-Alexander',
  'TEAM_ID': 1610612760,
  'TEAM_ABBREVIATION': 'OKC',
  'TEAM_NAME': 'Oklahoma City Thunder',
  'GAME_ID': '0022500001',
  'GAME_DATE': '2025-10-21',
  'MATCHUP': 'OKC vs. HOU',
  'WL': 'W',
  'MIN': 47,
  'FGM': 12,
  'FGA': 26,
  'FG_PCT': 0.462,
  'FG3M': 1,
  'FG3A': 9,
  'FG3_PCT': 0.111,
  'FTM': 10,
  'FTA': 14,
  'FT_PCT': 0.714,
  'OREB': 0,
  'DREB': 5,
  'REB': 5,
  'AST': 5,
  'STL': 2,
  'BLK': 2,
  'TOV': 3,
  'PF': 2,
  'PTS': 35,
  'PLUS_MINUS': 3,
  'FANTASY_PTS': 57.5,
  'VIDEO_AVAILABLE': 1},
 {'SEASON_ID': '22025',
  'PLAYER_ID': 1627936,
  'PLAYER_NAME': 'Alex Caruso',
  'TEAM_ID': 1610612760,
  'TEAM_ABBREVIATION': 'OKC',
  'TEAM_NAME': 'Oklahoma City Thunder',
  'GAME_ID': '0022500001',
  'GAME_DATE': '2025-10-21',
  'MATCHUP': 'OKC vs. HOU',
  'WL': 'W',
  'MIN': 30,
  'FGM': 3,
  'FGA': 9,
  'FG_PCT': 0.333,
  'FG3M': 2,
  'FG3A': 6,
  'FG3_PCT': 0.333,
  'FTM': 0,
  'FTA': 0,
  'FT_PCT': None,
  'OREB': 0,
  'DREB': 2,
  'REB': 2,
  'AST': 3,
  'STL': 2,
  'BLK': 1,
  'TOV': 0,
  'PF': 2,
  'PTS': 8,
  'PLUS_MINUS': -15,
  'FANTASY_PTS': 23.9,
  'VIDEO_AVAILABLE': 1},
 {'SEASON_ID': '22025',
  'PLAYER_ID': 1642263,
  'PLAYER_NAME': 'Reed Sheppard',
  'TEAM_ID': 1610612745,
  'TEAM_ABBREVIATION': 'HOU',
  'TEAM_NAME': 'Houston Rockets',
  'GAME_ID': '0022500001',
  'GAME_DATE': '2025-10-21',
  'MATCHUP': 'HOU @ OKC',
  'WL': 'L',
  'MIN': 28,
  'FGM': 3,
  'FGA': 11,
  'FG_PCT': 0.273,
  'FG3M': 2,
  'FG3A': 7,
  'FG3_PCT': 0.286,
  'FTM': 1,
  'FTA': 2,
  'FT_PCT': 0.5,
  'OREB': 1,
  'DREB': 1,
  'REB': 2,
  'AST': 4,
  'STL': 1,
  'BLK': 1,
  'TOV': 2,
  'PF': 1,
  'PTS': 9,
  'PLUS_MINUS': 0,
  'FANTASY_PTS': 21.4,
  'VIDEO_AVAILABLE': 1},
 {'SEASON_ID': '22025',
  'PLAYER_ID': 1641708,
  'PLAYER_NAME': 'Amen Thompson',
  'TEAM_ID': 1610612745,
  'TEAM_ABBREVIATION': 'HOU',
  'TEAM_NAME': 'Houston Rockets',
  'GAME_ID': '0022500001',
  'GAME_DATE': '2025-10-21',
  'MATCHUP': 'HOU @ OKC',
  'WL': 'L',
  'MIN': 39,
  'FGM': 8,
  'FGA': 17,
  'FG_PCT': 0.471,
  'FG3M': 0,
  'FG3A': 7,
  'FG3_PCT': 0.0,
  'FTM': 2,
  'FTA': 2,
  'FT_PCT': 1.0,
  'OREB': 2,
  'DREB': 2,
  'REB': 4,
  'AST': 5,
  'STL': 1,
  'BLK': 1,
  'TOV': 4,
  'PF': 3,
  'PTS': 18,
  'PLUS_MINUS': -11,
  'FANTASY_PTS': 32.3,
  'VIDEO_AVAILABLE': 1},
 {'SEASON_ID': '22025',
  'PLAYER_ID': 1631095,
  'PLAYER_NAME': 'Jabari Smith Jr.',
  'TEAM_ID': 1610612745,
  'TEAM_ABBREVIATION': 'HOU',
  'TEAM_NAME': 'Houston Rockets',
  'GAME_ID': '0022500001',
  'GAME_DATE': '2025-10-21',
  'MATCHUP': 'HOU @ OKC',
  'WL': 'L',
  'MIN': 42,
  'FGM': 7,
  'FGA': 15,
  'FG_PCT': 0.467,
  'FG3M': 2,
  'FG3A': 6,
  'FG3_PCT': 0.333,
  'FTM': 0,
  'FTA': 0,
  'FT_PCT': None,
  'OREB': 3,
  'DREB': 2,
  'REB': 5,
  'AST': 0,
  'STL': 1,
  'BLK': 0,
  'TOV': 0,
  'PF': 4,
  'PTS': 16,
  'PLUS_MINUS': 2,
  'FANTASY_PTS': 25.0,
  'VIDEO_AVAILABLE': 1},
 {'SEASON_ID': '22025',
  'PLAYER_ID': 1630578,
  'PLAYER_NAME': 'Alperen Sengun',
  'TEAM_ID': 1610612745,
  'TEAM_ABBREVIATION': 'HOU',
  'TEAM_NAME': 'Houston Rockets',
  'GAME_ID': '0022500001',
  'GAME_DATE': '2025-10-21',
  'MATCHUP': 'HOU @ OKC',
  'WL': 'L',
  'MIN': 49,
  'FGM': 12,
  'FGA': 24,
  'FG_PCT': 0.5,
  'FG3M': 5,
  'FG3A': 8,
  'FG3_PCT': 0.625,
  'FTM': 10,
  'FTA': 11,
  'FT_PCT': 0.909,
  'OREB': 4,
  'DREB': 7,
  'REB': 11,
  'AST': 7,
  'STL': 2,
  'BLK': 1,
  'TOV': 4,
  'PF': 5,
  'PTS': 39,
  'PLUS_MINUS': 9,
  'FANTASY_PTS': 67.7,
  'VIDEO_AVAILABLE': 1},
 {'SEASON_ID': '22025',
  'PLAYER_ID': 1629006,
  'PLAYER_NAME': 'Josh Okogie',
  'TEAM_ID': 1610612745,
  'TEAM_ABBREVIATION': 'HOU',
  'TEAM_NAME': 'Houston Rockets',
  'GAME_ID': '0022500001',
  'GAME_DATE': '2025-10-21',
  'MATCHUP': 'HOU @ OKC',
  'WL': 'L',
  'MIN': 20,
  'FGM': 1,
  'FGA': 3,
  'FG_PCT': 0.333,
  'FG3M': 1,
  'FG3A': 3,
  'FG3_PCT': 0.333,
  'FTM': 5,
  'FTA': 6,
  'FT_PCT': 0.833,
  'OREB': 1,
  'DREB': 1,
  'REB': 2,
  'AST': 1,
  'STL': 0,
  'BLK': 1,
  'TOV': 0,
  'PF': 2,
  'PTS': 8,
  'PLUS_MINUS': -8,
  'FANTASY_PTS': 14.9,
  'VIDEO_AVAILABLE': 1},
 {'SEASON_ID': '22025',
  'PLAYER_ID': 203991,
  'PLAYER_NAME': 'Clint Capela',
  'TEAM_ID': 1610612745,
  'TEAM_ABBREVIATION': 'HOU',
  'TEAM_NAME': 'Houston Rockets',
  'GAME_ID': '0022500001',
  'GAME_DATE': '2025-10-21',
  'MATCHUP': 'HOU @ OKC',
  'WL': 'L',
  'MIN': 8,
  'FGM': 1,
  'FGA': 1,
  'FG_PCT': 1.0,
  'FG3M': 0,
  'FG3A': 0,
  'FG3_PCT': None,
  'FTM': 2,
  'FTA': 2,
  'FT_PCT': 1.0,
  'OREB': 0,
  'DREB': 0,
  'REB': 0,
  'AST': 0,
  'STL': 1,
  'BLK': 0,
  'TOV': 1,
  'PF': 0,
  'PTS': 4,
  'PLUS_MINUS': 5,
  'FANTASY_PTS': 6.0,
  'VIDEO_AVAILABLE': 1},
 {'SEASON_ID': '22025',
  'PLAYER_ID': 203500,
  'PLAYER_NAME': 'Steven Adams',
  'TEAM_ID': 1610612745,
  'TEAM_ABBREVIATION': 'HOU',
  'TEAM_NAME': 'Houston Rockets',
  'GAME_ID': '0022500001',
  'GAME_DATE': '2025-10-21',
  'MATCHUP': 'HOU @ OKC',
  'WL': 'L',
  'MIN': 37,
  'FGM': 1,
  'FGA': 4,
  'FG_PCT': 0.25,
  'FG3M': 0,
  'FG3A': 0,
  'FG3_PCT': None,
  'FTM': 2,
  'FTA': 2,
  'FT_PCT': 1.0,
  'OREB': 5,
  'DREB': 8,
  'REB': 13,
  'AST': 3,
  'STL': 0,
  'BLK': 0,
  'TOV': 3,
  'PF': 4,
  'PTS': 4,
  'PLUS_MINUS': 2,
  'FANTASY_PTS': 21.1,
  'VIDEO_AVAILABLE': 1},
 {'SEASON_ID': '22025',
  'PLAYER_ID': 201142,
  'PLAYER_NAME': 'Kevin Durant',
  'TEAM_ID': 1610612745,
  'TEAM_ABBREVIATION': 'HOU',
  'TEAM_NAME': 'Houston Rockets',
  'GAME_ID': '0022500001',
  'GAME_DATE': '2025-10-21',
  'MATCHUP': 'HOU @ OKC',
  'WL': 'L',
  'MIN': 47,
  'FGM': 9,
  'FGA': 16,
  'FG_PCT': 0.563,
  'FG3M': 0,
  'FG3A': 4,
  'FG3_PCT': 0.0,
  'FTM': 5,
  'FTA': 6,
  'FT_PCT': 0.833,
  'OREB': 0,
  'DREB': 9,
  'REB': 9,
  'AST': 3,
  'STL': 0,
  'BLK': 0,
  'TOV': 4,
  'PF': 6,
  'PTS': 23,
  'PLUS_MINUS': 0,
  'FANTASY_PTS': 34.3,
  'VIDEO_AVAILABLE': 1},
 {'SEASON_ID': '22025',
  'PLAYER_ID': 1631222,
  'PLAYER_NAME': 'Jake LaRavia',
  'TEAM_ID': 1610612747,
  'TEAM_ABBREVIATION': 'LAL',
  'TEAM_NAME': 'Los Angeles Lakers',
  'GAME_ID': '0022500002',
  'GAME_DATE': '2025-10-21',
  'MATCHUP': 'LAL vs. GSW',
  'WL': 'L',
  'MIN': 16,
  'FGM': 2,
  'FGA': 4,
  'FG_PCT': 0.5,
  'FG3M': 1,
  'FG3A': 2,
  'FG3_PCT': 0.5,
  'FTM': 0,
  'FTA': 2,
  'FT_PCT': 0.0,
  'OREB': 2,
  'DREB': 1,
  'REB': 3,
  'AST': 0,
  'STL': 0,
  'BLK': 0,
  'TOV': 0,
  'PF': 1,
  'PTS': 5,
  'PLUS_MINUS': -5,
  'FANTASY_PTS': 8.6,
  'VIDEO_AVAILABLE': 1},
 {'SEASON_ID': '22025',
  'PLAYER_ID': 1627741,
  'PLAYER_NAME': 'Buddy Hield',
  'TEAM_ID': 1610612744,
  'TEAM_ABBREVIATION': 'GSW',
  'TEAM_NAME': 'Golden State Warriors',
  'GAME_ID': '0022500002',
  'GAME_DATE': '2025-10-21',
  'MATCHUP': 'GSW @ LAL',
  'WL': 'W',
  'MIN': 22,
  'FGM': 6,
  'FGA': 11,
  'FG_PCT': 0.545,
  'FG3M': 5,
  'FG3A': 10,
  'FG3_PCT': 0.5,
  'FTM': 0,
  'FTA': 0,
  'FT_PCT': None,
  'OREB': 0,
  'DREB': 1,
  'REB': 1,
  'AST': 0,
  'STL': 1,
  'BLK': 0,
  'TOV': 2,
  'PF': 0,
  'PTS': 17,
  'PLUS_MINUS': 5,
  'FANTASY_PTS': 19.2,
  'VIDEO_AVAILABLE': 1},
 {'SEASON_ID': '22025',
  'PLAYER_ID': 1629637,
  'PLAYER_NAME': 'Jaxson Hayes',
  'TEAM_ID': 1610612747,
  'TEAM_ABBREVIATION': 'LAL',
  'TEAM_NAME': 'Los Angeles Lakers',
  'GAME_ID': '0022500002',
  'GAME_DATE': '2025-10-21',
  'MATCHUP': 'LAL vs. GSW',
  'WL': 'L',
  'MIN': 14,
  'FGM': 2,
  'FGA': 3,
  'FG_PCT': 0.667,
  'FG3M': 0,
  'FG3A': 0,
  'FG3_PCT': None,
  'FTM': 0,
  'FTA': 0,
  'FT_PCT': None,
  'OREB': 2,
  'DREB': 4,
  'REB': 6,
  'AST': 1,
  'STL': 0,
  'BLK': 0,
  'TOV': 1,
  'PF': 2,
  'PTS': 4,
  'PLUS_MINUS': -6,
  'FANTASY_PTS': 11.7,
  'VIDEO_AVAILABLE': 1},
 {'SEASON_ID': '22025',
  'PLAYER_ID': 202710,
  'PLAYER_NAME': 'Jimmy Butler III',
  'TEAM_ID': 1610612744,
  'TEAM_ABBREVIATION': 'GSW',
  'TEAM_NAME': 'Golden State Warriors',
  'GAME_ID': '0022500002',
  'GAME_DATE': '2025-10-21',
  'MATCHUP': 'GSW @ LAL',
  'WL': 'W',
  'MIN': 35,
  'FGM': 7,
  'FGA': 14,
  'FG_PCT': 0.5,
  'FG3M': 1,
  'FG3A': 2,
  'FG3_PCT': 0.5,
  'FTM': 16,
  'FTA': 16,
  'FT_PCT': 1.0,
  'OREB': 2,
  'DREB': 3,
  'REB': 5,
  'AST': 4,
  'STL': 1,
  'BLK': 0,
  'TOV': 1,
  'PF': 4,
  'PTS': 31,
  'PLUS_MINUS': 20,
  'FANTASY_PTS': 45.0,
  'VIDEO_AVAILABLE': 1},
 {'SEASON_ID': '22025',
  'PLAYER_ID': 203110,
  'PLAYER_NAME': 'Draymond Green',
  'TEAM_ID': 1610612744,
  'TEAM_ABBREVIATION': 'GSW',
  'TEAM_NAME': 'Golden State Warriors',
  'GAME_ID': '0022500002',
  'GAME_DATE': '2025-10-21',
  'MATCHUP': 'GSW @ LAL',
  'WL': 'W',
  'MIN': 28,
  'FGM': 3,
  'FGA': 6,
  'FG_PCT': 0.5,
  'FG3M': 1,
  'FG3A': 3,
  'FG3_PCT': 0.333,
  'FTM': 1,
  'FTA': 3,
  'FT_PCT': 0.333,
  'OREB': 1,
  'DREB': 6,
  'REB': 7,
  'AST': 9,
  'STL': 1,
  'BLK': 2,
  'TOV': 4,
  'PF': 5,
  'PTS': 8,
  'PLUS_MINUS': 20,
  'FANTASY_PTS': 34.9,
  'VIDEO_AVAILABLE': 1},
 {'SEASON_ID': '22025',
  'PLAYER_ID': 1629216,
  'PLAYER_NAME': 'Gabe Vincent',
  'TEAM_ID': 1610612747,
  'TEAM_ABBREVIATION': 'LAL',
  'TEAM_NAME': 'Los Angeles Lakers',
  'GAME_ID': '0022500002',
  'GAME_DATE': '2025-10-21',
  'MATCHUP': 'LAL vs. GSW',
  'WL': 'L',
  'MIN': 29,
  'FGM': 1,
  'FGA': 4,
  'FG_PCT': 0.25,
  'FG3M': 1,
  'FG3A': 4,
  'FG3_PCT': 0.25,
  'FTM': 0,
  'FTA': 0,
  'FT_PCT': None,
  'OREB': 0,
  'DREB': 0,
  'REB': 0,
  'AST': 1,
  'STL': 1,
  'BLK': 0,
  'TOV': 0,
  'PF': 3,
  'PTS': 3,
  'PLUS_MINUS': -5,
  'FANTASY_PTS': 7.5,
  'VIDEO_AVAILABLE': 1},
 {'SEASON_ID': '22025',
  'PLAYER_ID': 1630228,
  'PLAYER_NAME': 'Jonathan Kuminga',
  'TEAM_ID': 1610612744,
  'TEAM_ABBREVIATION': 'GSW',
  'TEAM_NAME': 'Golden State Warriors',
  'GAME_ID': '0022500002',
  'GAME_DATE': '2025-10-21',
  'MATCHUP': 'GSW @ LAL',
  'WL': 'W',
  'MIN': 33,
  'FGM': 6,
  'FGA': 11,
  'FG_PCT': 0.545,
  'FG3M': 4,
  'FG3A': 6,
  'FG3_PCT': 0.667,
  'FTM': 1,
  'FTA': 2,
  'FT_PCT': 0.5,
  'OREB': 3,
  'DREB': 6,
  'REB': 9,
  'AST': 6,
  'STL': 1,
  'BLK': 0,
  'TOV': 2,
  'PF': 3,
  'PTS': 17,
  'PLUS_MINUS': 4,
  'FANTASY_PTS': 37.8,
  'VIDEO_AVAILABLE': 1},
 {'SEASON_ID': '22025',
  'PLAYER_ID': 1629029,
  'PLAYER_NAME': 'Luka Dončić',
  'TEAM_ID': 1610612747,
  'TEAM_ABBREVIATION': 'LAL',
  'TEAM_NAME': 'Los Angeles Lakers',
  'GAME_ID': '0022500002',
  'GAME_DATE': '2025-10-21',
  'MATCHUP': 'LAL vs. GSW',
  'WL': 'L',
  'MIN': 41,
  'FGM': 17,
  'FGA': 27,
  'FG_PCT': 0.63,
  'FG3M': 2,
  'FG3A': 10,
  'FG3_PCT': 0.2,
  'FTM': 7,
  'FTA': 10,
  'FT_PCT': 0.7,
  'OREB': 0,
  'DREB': 12,
  'REB': 12,
  'AST': 9,
  'STL': 2,
  'BLK': 1,
  'TOV': 3,
  'PF': 1,
  'PTS': 43,
  'PLUS_MINUS': -8,
  'FANTASY_PTS': 76.9,
  'VIDEO_AVAILABLE': 1},
 {'SEASON_ID': '22025',
  'PLAYER_ID': 201143,
  'PLAYER_NAME': 'Al Horford',
  'TEAM_ID': 1610612744,
  'TEAM_ABBREVIATION': 'GSW',
  'TEAM_NAME': 'Golden State Warriors',
  'GAME_ID': '0022500002',
  'GAME_DATE': '2025-10-21',
  'MATCHUP': 'GSW @ LAL',
  'WL': 'W',
  'MIN': 20,
  'FGM': 2,
  'FGA': 7,
  'FG_PCT': 0.286,
  'FG3M': 1,
  'FG3A': 4,
  'FG3_PCT': 0.25,
  'FTM': 0,
  'FTA': 0,
  'FT_PCT': None,
  'OREB': 0,
  'DREB': 5,
  'REB': 5,
  'AST': 1,
  'STL': 0,
  'BLK': 0,
  'TOV': 2,
  'PF': 4,
  'PTS': 5,
  'PLUS_MINUS': -10,
  'FANTASY_PTS': 10.5,
  'VIDEO_AVAILABLE': 1},
 {'SEASON_ID': '22025',
  'PLAYER_ID': 1642349,
  'PLAYER_NAME': 'Ajay Mitchell',
  'TEAM_ID': 1610612760,
  'TEAM_ABBREVIATION': 'OKC',
  'TEAM_NAME': 'Oklahoma City Thunder',
  'GAME_ID': '0022500001',
  'GAME_DATE': '2025-10-21',
  'MATCHUP': 'OKC vs. HOU',
  'WL': 'W',
  'MIN': 15,
  'FGM': 6,
  'FGA': 12,
  'FG_PCT': 0.5,
  'FG3M': 3,
  'FG3A': 6,
  'FG3_PCT': 0.5,
  'FTM': 1,
  'FTA': 1,
  'FT_PCT': 1.0,
  'OREB': 1,
  'DREB': 1,
  'REB': 2,
  'AST': 2,
  'STL': 0,
  'BLK': 1,
  'TOV': 0,
  'PF': 2,
  'PTS': 16,
  'PLUS_MINUS': 2,
  'FANTASY_PTS': 24.4,
  'VIDEO_AVAILABLE': 1},
 {'SEASON_ID': '22025',
  'PLAYER_ID': 1629060,
  'PLAYER_NAME': 'Rui Hachimura',
  'TEAM_ID': 1610612747,
  'TEAM_ABBREVIATION': 'LAL',
  'TEAM_NAME': 'Los Angeles Lakers',
  'GAME_ID': '0022500002',
  'GAME_DATE': '2025-10-21',
  'MATCHUP': 'LAL vs. GSW',
  'WL': 'L',
  'MIN': 35,
  'FGM': 3,
  'FGA': 6,
  'FG_PCT': 0.5,
  'FG3M': 3,
  'FG3A': 6,
  'FG3_PCT': 0.5,
  'FTM': 0,
  'FTA': 0,
  'FT_PCT': None,
  'OREB': 0,
  'DREB': 4,
  'REB': 4,
  'AST': 3,
  'STL': 0,
  'BLK': 0,
  'TOV': 1,
  'PF': 2,
  'PTS': 9,
  'PLUS_MINUS': -6,
  'FANTASY_PTS': 17.3,
  'VIDEO_AVAILABLE': 1},
 {'SEASON_ID': '22025',
  'PLAYER_ID': 1630611,
  'PLAYER_NAME': 'Gui Santos',
  'TEAM_ID': 1610612744,
  'TEAM_ABBREVIATION': 'GSW',
  'TEAM_NAME': 'Golden State Warriors',
  'GAME_ID': '0022500002',
  'GAME_DATE': '2025-10-21',
  'MATCHUP': 'GSW @ LAL',
  'WL': 'W',
  'MIN': 3,
  'FGM': 0,
  'FGA': 0,
  'FG_PCT': None,
  'FG3M': 0,
  'FG3A': 0,
  'FG3_PCT': None,
  'FTM': 0,
  'FTA': 0,
  'FT_PCT': None,
  'OREB': 0,
  'DREB': 0,
  'REB': 0,
  'AST': 0,
  'STL': 0,
  'BLK': 0,
  'TOV': 1,
  'PF': 0,
  'PTS': 0,
  'PLUS_MINUS': 0,
  'FANTASY_PTS': -1.0,
  'VIDEO_AVAILABLE': 1},
 {'SEASON_ID': '22025',
  'PLAYER_ID': 1642954,
  'PLAYER_NAME': 'Will Richard',
  'TEAM_ID': 1610612744,
  'TEAM_ABBREVIATION': 'GSW',
  'TEAM_NAME': 'Golden State Warriors',
  'GAME_ID': '0022500002',
  'GAME_DATE': '2025-10-21',
  'MATCHUP': 'GSW @ LAL',
  'WL': 'W',
  'MIN': 14,
  'FGM': 2,
  'FGA': 2,
  'FG_PCT': 1.0,
  'FG3M': 1,
  'FG3A': 1,
  'FG3_PCT': 1.0,
  'FTM': 0,
  'FTA': 0,
  'FT_PCT': None,
  'OREB': 1,
  'DREB': 0,
  'REB': 1,
  'AST': 1,
  'STL': 1,
  'BLK': 0,
  'TOV': 0,
  'PF': 2,
  'PTS': 5,
  'PLUS_MINUS': -11,
  'FANTASY_PTS': 10.7,
  'VIDEO_AVAILABLE': 1},
 {'SEASON_ID': '22025',
  'PLAYER_ID': 1627780,
  'PLAYER_NAME': 'Gary Payton II',
  'TEAM_ID': 1610612744,
  'TEAM_ABBREVIATION': 'GSW',
  'TEAM_NAME': 'Golden State Warriors',
  'GAME_ID': '0022500002',
  'GAME_DATE': '2025-10-21',
  'MATCHUP': 'GSW @ LAL',
  'WL': 'W',
  'MIN': 12,
  'FGM': 3,
  'FGA': 6,
  'FG_PCT': 0.5,
  'FG3M': 0,
  'FG3A': 1,
  'FG3_PCT': 0.0,
  'FTM': 0,
  'FTA': 0,
  'FT_PCT': None,
  'OREB': 1,
  'DREB': 1,
  'REB': 2,
  'AST': 1,
  'STL': 1,
  'BLK': 1,
  'TOV': 3,
  'PF': 3,
  'PTS': 6,
  'PLUS_MINUS': 3,
  'FANTASY_PTS': 12.9,
  'VIDEO_AVAILABLE': 1},
 {'SEASON_ID': '22025',
  'PLAYER_ID': 1631106,
  'PLAYER_NAME': 'Tari Eason',
  'TEAM_ID': 1610612745,
  'TEAM_ABBREVIATION': 'HOU',
  'TEAM_NAME': 'Houston Rockets',
  'GAME_ID': '0022500001',
  'GAME_DATE': '2025-10-21',
  'MATCHUP': 'HOU @ OKC',
  'WL': 'L',
  'MIN': 22,
  'FGM': 1,
  'FGA': 6,
  'FG_PCT': 0.167,
  'FG3M': 1,
  'FG3A': 4,
  'FG3_PCT': 0.25,
  'FTM': 0,
  'FTA': 0,
  'FT_PCT': None,
  'OREB': 0,
  'DREB': 6,
  'REB': 6,
  'AST': 0,
  'STL': 0,
  'BLK': 1,
  'TOV': 4,
  'PF': 1,
  'PTS': 3,
  'PLUS_MINUS': -4,
  'FANTASY_PTS': 9.2,
  'VIDEO_AVAILABLE': 1},
 {'SEASON_ID': '22025',
  'PLAYER_ID': 1641764,
  'PLAYER_NAME': 'Brandin Podziemski',
  'TEAM_ID': 1610612744,
  'TEAM_ABBREVIATION': 'GSW',
  'TEAM_NAME': 'Golden State Warriors',
  'GAME_ID': '0022500002',
  'GAME_DATE': '2025-10-21',
  'MATCHUP': 'GSW @ LAL',
  'WL': 'W',
  'MIN': 33,
  'FGM': 3,
  'FGA': 7,
  'FG_PCT': 0.429,
  'FG3M': 1,
  'FG3A': 4,
  'FG3_PCT': 0.25,
  'FTM': 0,
  'FTA': 0,
  'FT_PCT': None,
  'OREB': 1,
  'DREB': 6,
  'REB': 7,
  'AST': 2,
  'STL': 1,
  'BLK': 0,
  'TOV': 1,
  'PF': 2,
  'PTS': 7,
  'PLUS_MINUS': 13,
  'FANTASY_PTS': 20.4,
  'VIDEO_AVAILABLE': 1},
 {'SEASON_ID': '22025',
  'PLAYER_ID': 1629028,
  'PLAYER_NAME': 'Deandre Ayton',
  'TEAM_ID': 1610612747,
  'TEAM_ABBREVIATION': 'LAL',
  'TEAM_NAME': 'Los Angeles Lakers',
  'GAME_ID': '0022500002',
  'GAME_DATE': '2025-10-21',
  'MATCHUP': 'LAL vs. GSW',
  'WL': 'L',
  'MIN': 34,
  'FGM': 5,
  'FGA': 7,
  'FG_PCT': 0.714,
  'FG3M': 0,
  'FG3A': 0,
  'FG3_PCT': None,
  'FTM': 0,
  'FTA': 2,
  'FT_PCT': 0.0,
  'OREB': 2,
  'DREB': 4,
  'REB': 6,
  'AST': 0,
  'STL': 0,
  'BLK': 1,
  'TOV': 4,
  'PF': 3,

In [4]:
extract_df.keys()

Index(['SEASON_ID', 'PLAYER_ID', 'PLAYER_NAME', 'TEAM_ID', 'TEAM_ABBREVIATION',
       'TEAM_NAME', 'GAME_ID', 'GAME_DATE', 'MATCHUP', 'WL', 'MIN', 'FGM',
       'FGA', 'FG_PCT', 'FG3M', 'FG3A', 'FG3_PCT', 'FTM', 'FTA', 'FT_PCT',
       'OREB', 'DREB', 'REB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS',
       'PLUS_MINUS', 'FANTASY_PTS', 'VIDEO_AVAILABLE'],
      dtype='str')

In [5]:
from nba_api.stats.static import players

In [6]:
player_search = players.find_players_by_full_name('Luka Doncic')

In [7]:
player_search

[{'id': 1629029,
  'full_name': 'Luka Dončić',
  'first_name': 'Luka',
  'last_name': 'Dončić',
  'is_active': True}]

In [40]:
from nba_api.stats.endpoints import scheduleleaguev2

In [41]:
schedule = scheduleleaguev2.ScheduleLeagueV2()

In [10]:
schedule.get_data_frames()[0]

,leagueId,seasonYear,gameDate,gameId,gameCode,gameStatus,gameStatusText,gameSequence,gameDateEst,gameTimeEst,...,awayOttBroadcasters_broadcasterMedia,awayOttBroadcasters_broadcasterId,awayOttBroadcasters_broadcasterDisplay,awayOttBroadcasters_broadcasterAbbreviation,awayOttBroadcasters_broadcasterDescription,awayOttBroadcasters_tapeDelayComments,awayOttBroadcasters_broadcasterVideoLink,awayOttBroadcasters_broadcasterTeamId,awayOttBroadcasters_broadcasterRanking,awayOttBroadcasters_localizationRegion
0,00,2025-26,10/02/2025 00:00:00,0012500008,20251002/PHINYK,3,Final,1,2025-10-02T00:00:00Z,1900-01-01T12:00:00Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN
1,00,2025-26,10/03/2025 00:00:00,0012500001,20251003/PHXLAL,3,Final,2,2025-10-03T00:00:00Z,1900-01-01T22:00:00Z,...,ott,1001033.0,Suns+,DTC-PHX,,,,1.610613e+09,None,
2,00,2025-26,10/03/2025 00:00:00,0012500009,20251003/MELNOP,3,Final,1,2025-10-03T00:00:00Z,1900-01-01T05:30:00Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN
3,00,2025-26,10/04/2025 00:00:00,0012500010,20251004/NYKPHI,3,Final,1,2025-10-04T00:00:00Z,1900-01-01T11:00:00Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN
4,00,2025-26,10/04/2025 00:00:00,0012500011,20251004/SEMNOP,3,Final,5,2025-10-04T00:00:00Z,1900-01-01T23:00:00Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1317,00,2025-26,06/08/2026 00:00:00,0042500403,,1,8:30 pm ET,1,2026-06-08T00:00:00Z,1900-01-01T20:30:00Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN
1318,00,2025-26,06/10/2026 00:00:00,0042500404,,1,8:30 pm ET,1,2026-06-10T00:00:00Z,1900-01-01T20:30:00Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN
1319,00,2025-26,06/13/2026 00:00:00,0042500405,,1,8:30 pm ET,1,2026-06-13T00:00:00Z,1900-01-01T20:30:00Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN
1320,00,2025-26,06/16/2026 00:00:00,0042500406,,1,8:30 pm ET,1,2026-06-16T00:00:00Z,1900-01-01T20:30:00Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN
1321,00,2025-26,06/19/2026 00:00:00,0042500407,,1,8:30 pm ET,1,2026-06-19T00:00:00Z,1900-01-01T20:30:00Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN

In [11]:
schedule.get_data_frames()[1]

,leagueId,seasonYear,weekNumber,weekName,startDate,endDate
0,00,2025-26,1,Week 1,2025-10-21T00:00:00Z,2025-10-26T00:00:00Z
1,00,2025-26,2,Week 2,2025-10-27T00:00:00Z,2025-11-02T00:00:00Z
2,00,2025-26,3,Week 3,2025-11-03T00:00:00Z,2025-11-09T00:00:00Z
3,00,2025-26,4,Week 4,2025-11-10T00:00:00Z,2025-11-16T00:00:00Z
4,00,2025-26,5,Week 5,2025-11-17T00:00:00Z,2025-11-23T00:00:00Z
5,00,2025-26,6,Week 6,2025-11-24T00:00:00Z,2025-11-30T00:00:00Z
6,00,2025-26,7,Week 7,2025-12-01T00:00:00Z,2025-12-07T00:00:00Z
7,00,2025-26,8,Week 8,2025-12-08T00:00:00Z,2025-12-14T00:00:00Z
8,00,2025-26,9,Week 9,2025-12-15T00:00:00Z,2025-12-21T00:00:00Z
9,00,2025-26,10,Week 10,2025-12-22T00:00:00Z,2025-12-28T00:00:00Z
10,00,2025-26,11,Week 11,2025-12-29T00:00:00Z,2026-01-04T00:00:00Z
11,00,2025-26,12,Week 12,2026-01-05T00:00:00Z,2026-01-11T00:00:00Z
12,00,2025-26,13,Week 13,2026-01-12T00:00:00Z,2026-01-18T00:00:00Z
13,00,2025-26,14,Week 14,2026-01-19T00:00:00Z,2026-01-25T00:00:00Z
14,00,2025-26,15,Week 15,2026-01-26T00:00:00Z,2026-02-01T00:00:00Z
15,00,2025-26,16,Week 16,2026-02-02T00:00:00Z,2026-02-08T00:00:00Z
16,00,2025-26,17,Week 17,2026-02-09T00:00:00Z,2026-02-15T00:00:00Z
17,00,2025-26,18,Week 18,2026-02-16T00:00:00Z,2026-02-22T00:00:00Z
18,00,2025-26,19,Week 19,2026-02-23T00:00:00Z,2026-03-01T00:00:00Z
19,00,2025-26,20,Week 20,2026-03-02T00:00:00Z,2026-03-08T00:00:00Z
20,00,2025-26,21,Week 21,2026-03-09T00:00:00Z,2026-03-15T00:00:00Z
21,00,2025-26,22,Week 22,2026-03-16T00:00:00Z,2026-03-22T00:00:00Z
22,00,2025-26,23,Week 23,2026-03-23T00:00:00Z,2026-03-29T00:00:00Z
23,00,2025-26,24,Week 24,2026-03-30T00:00:00Z,2026-04-05T00:00:00Z
24,00,2025-26,25,Week 25,2026-04-06T00:00:00Z,2026-04-12T00:00:00Z
25,00,2025-26,26,Week 26,2026-04-13T00:00:00Z,2026-04-19T00:00:00Z
26,00,2025-26,27,Week 27,2026-04-20T00:00:00Z,2026-04-26T00:00:00Z
27,00,2025-26,28,Week 28,2026-04-27T00:00:00Z,2026-05-03T00:00:00Z
28,00,2025-26,29,Week 29,2026-05-04T00:00:00Z,2026-05-10T00:00:00Z
29,00,2025-26,30,Week 30,2026-05-11T00:00:00Z,2026-05-17T00:00:00Z
30,00,2025-26,31,Week 31,2026-05-18T00:00:00Z,2026-05-24T00:00:00Z
31,00,2025-26,32,Week 32,2026-05-25T00:00:00Z,2026-05-31T00:00:00Z
32,00,2025-26,33,Week 33,2026-06-01T00:00:00Z,2026-06-07T00:00:00Z
33,00,2025-26,34,Week 34,2026-06-08T00:00:00Z,2026-06-14T00:00:00Z
34,00,2025-26,35,Week 35,2026-06-15T00:00:00Z,2026-06-21T00:00:00Z
35,00,2025-26,26,Week 26,2026-04-13T00:00:00Z,2026-04-19T00:00:00Z
36,00,2025-26,9,Week 9,2025-12-15T00:00:00Z,2025-12-21T00:00:00Z
37,00,2025-26,17,All-Star,2026-02-09T00:00:00Z,2026-02-15T00:00:00Z

In [23]:
schedule_json = json.loads(schedule.get_json())

In [42]:
schedule_json.keys()

dict_keys(['meta', 'leagueSchedule'])

In [43]:
schedule_json['meta']

{'version': 1,
 'request': 'http://nba.cloud/league/00/2025-26/scheduleleaguev2?Format=json',
 'time': '2026-03-05T21:00:10.01Z'}

In [16]:
schedule_json['leagueSchedule'].keys()

dict_keys(['seasonYear', 'leagueId', 'gameDates', 'weeks'])

In [44]:
schedule_json['leagueSchedule']['seasonYear']

'2025-26'

In [37]:
schedule_json['leagueSchedule']['gameDates'][0]

{'gameDate': '10/02/2025 00:00:00',
 'games': [{'gameId': '0012500008',
   'gameCode': '20251002/PHINYK',
   'gameStatus': 3,
   'gameStatusText': 'Final',
   'gameSequence': 1,
   'gameDateEst': '2025-10-02T00:00:00Z',
   'gameTimeEst': '1900-01-01T12:00:00Z',
   'gameDateTimeEst': '2025-10-02T12:00:00Z',
   'gameDateUTC': '2025-10-02T04:00:00Z',
   'gameTimeUTC': '1900-01-01T16:00:00Z',
   'gameDateTimeUTC': '2025-10-02T16:00:00Z',
   'awayTeamTime': '2025-10-02T12:00:00Z',
   'homeTeamTime': '2025-10-02T12:00:00Z',
   'day': 'Thu',
   'monthNum': 10,
   'weekNumber': 0,
   'weekName': '',
   'ifNecessary': 'false',
   'seriesGameNumber': '',
   'gameLabel': 'Preseason',
   'gameSubLabel': 'NBA Abu Dhabi Game',
   'seriesText': 'Neutral Site',
   'arenaName': 'Etihad Arena',
   'arenaState': '',
   'arenaCity': 'Abu Dhabi',
   'postponedStatus': 'N',
   'branchLink': '',
   'gameSubtype': 'Global Games',
   'isNeutral': True,
   'broadcasters': {'nationalBroadcasters': [{'broadcasterScope': 'natl',
      'broadcasterMedia': 'tv',
      'broadcasterId': 7,
      'broadcasterDisplay': 'NBA TV',
      'broadcasterAbbreviation': 'NBA TV',
      'broadcasterDescription': 'Watch with League Pass or your TV subscription',
      'tapeDelayComments': '',
      'broadcasterVideoLink': '',
      'broadcasterTeamId': -1,
      'broadcasterRanking': None,
      'localizationRegion': ''}],
    'nationalRadioBroadcasters': [],
    'nationalOttBroadcasters': [],
    'homeTvBroadcasters': [{'broadcasterScope': 'home',
      'broadcasterMedia': 'tv',
      'broadcasterId': 100,
      'broadcasterDisplay': 'Gotham',
      'broadcasterAbbreviation': 'MSG',
      'broadcasterDescription': '',
      'tapeDelayComments': '',
      'broadcasterVideoLink': '',
      'broadcasterTeamId': 1610612752,
      'broadcasterRanking': None,
      'localizationRegion': ''}],
    'homeRadioBroadcasters': [],
    'homeOttBroadcasters': [],
    'awayTvBroadcasters': [],
    'awayRadioBroadcasters': [],
    'awayOttBroadcasters': []},
   'homeTeam': {'teamId': 1610612752,
    'teamName': 'Knicks',
    'teamCity': 'New York',
    'teamTricode': 'NYK',
    'teamSlug': 'knicks',
    'wins': 1,
    'losses': 0,
    'score': 99,
    'seed': 0},
   'awayTeam': {'teamId': 1610612755,
    'teamName': '76ers',
    'teamCity': 'Philadelphia',
    'teamTricode': 'PHI',
    'teamSlug': 'sixers',
    'wins': 0,
    'losses': 1,
    'score': 84,
    'seed': 0},
   'pointsLeaders': [{'personId': 1630178,
     'firstName': 'Tyrese',
     'lastName': 'Maxey',
     'teamId': 1610612755,
     'teamCity': 'Philadelphia',
     'teamName': '76ers',
     'teamTricode': 'PHI',
     'points': 14.0},
    {'personId': 1642845,
     'firstName': 'Valdez',
     'lastName': 'Edgecombe',
     'teamId': 1610612755,
     'teamCity': 'Philadelphia',
     'teamName': '76ers',
     'teamTricode': 'PHI',
     'points': 14.0}]}]}

In [39]:
schedule_json['leagueSchedule']['gameDates'][0]['games'][0].keys()

dict_keys(['gameId', 'gameCode', 'gameStatus', 'gameStatusText', 'gameSequence', 'gameDateEst', 'gameTimeEst', 'gameDateTimeEst', 'gameDateUTC', 'gameTimeUTC', 'gameDateTimeUTC', 'awayTeamTime', 'homeTeamTime', 'day', 'monthNum', 'weekNumber', 'weekName', 'ifNecessary', 'seriesGameNumber', 'gameLabel', 'gameSubLabel', 'seriesText', 'arenaName', 'arenaState', 'arenaCity', 'postponedStatus', 'branchLink', 'gameSubtype', 'isNeutral', 'broadcasters', 'homeTeam', 'awayTeam', 'pointsLeaders'])

In [55]:
from nba_api.stats.endpoints import commonallplayers

In [60]:
all_players = commonallplayers.CommonAllPlayers()

In [63]:
all_players.get_data_frames()[0].head()

,PERSON_ID,DISPLAY_LAST_COMMA_FIRST,DISPLAY_FIRST_LAST,ROSTERSTATUS,FROM_YEAR,TO_YEAR,PLAYERCODE,PLAYER_SLUG,TEAM_ID,TEAM_CITY,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CODE,TEAM_SLUG,GAMES_PLAYED_FLAG,OTHERLEAGUE_EXPERIENCE_CH
0,76001,"Abdelnaby, Alaa",Alaa Abdelnaby,0,1990,1994,HISTADD_alaa_abdelnaby,alaa_abdelnaby,0,,,,,NaN,Y,00
1,76002,"Abdul-Aziz, Zaid",Zaid Abdul-Aziz,0,1968,1977,HISTADD_zaid_abdul-aziz,zaid_abdul-aziz,0,,,,,NaN,Y,00
2,76003,"Abdul-Jabbar, Kareem",Kareem Abdul-Jabbar,0,1969,1988,HISTADD_kareem_abdul-jabbar,kareem_abdul-jabbar,0,,,,,NaN,Y,00
3,51,"Abdul-Rauf, Mahmoud",Mahmoud Abdul-Rauf,0,1990,2000,mahmoud_abdul-rauf,mahmoud_abdul-rauf,0,,,,,NaN,Y,00
4,1505,"Abdul-Wahad, Tariq",Tariq Abdul-Wahad,0,1997,2003,tariq_abdul-wahad,tariq_abdul-wahad,0,,,,,NaN,Y,00

In [64]:
from nba_api.stats.endpoints import leaguedashplayerbiostats

In [88]:
bio_data = leaguedashplayerbiostats.LeagueDashPlayerBioStats()

In [89]:
bio_data.get_data_frames()[0].head()

,PLAYER_ID,PLAYER_NAME,TEAM_ID,TEAM_ABBREVIATION,AGE,PLAYER_HEIGHT,PLAYER_HEIGHT_INCHES,PLAYER_WEIGHT,COLLEGE,COUNTRY,...,GP,PTS,REB,AST,NET_RATING,OREB_PCT,DREB_PCT,USG_PCT,TS_PCT,AST_PCT
0,1630639,A.J. Lawson,1610612761,TOR,25.0,6-6,78,179,South Carolina,Canada,...,14,49,23,3,-14.2,0.055,0.160,0.185,0.545,0.045
1,1631260,AJ Green,1610612749,MIL,26.0,6-4,76,190,Northern Iowa,USA,...,60,589,150,115,-2.0,0.009,0.073,0.128,0.611,0.086
2,1642358,AJ Johnson,1610612742,DAL,21.0,6-5,77,160,None,USA,...,36,103,43,32,-4.8,0.025,0.103,0.189,0.397,0.147
3,203932,Aaron Gordon,1610612743,DEN,30.0,6-8,80,235,Arizona,USA,...,25,432,155,64,13.5,0.052,0.162,0.227,0.622,0.132
4,1628988,Aaron Holiday,1610612745,HOU,29.0,6-0,72,185,UCLA,USA,...,42,231,37,37,4.3,0.011,0.054,0.171,0.568,0.098

In [68]:
bio_data.get_data_frames()[0].keys()

Index(['PLAYER_ID', 'PLAYER_NAME', 'TEAM_ID', 'TEAM_ABBREVIATION', 'AGE',
       'PLAYER_HEIGHT', 'PLAYER_HEIGHT_INCHES', 'PLAYER_WEIGHT', 'COLLEGE',
       'COUNTRY', 'DRAFT_YEAR', 'DRAFT_ROUND', 'DRAFT_NUMBER', 'GP', 'PTS',
       'REB', 'AST', 'NET_RATING', 'OREB_PCT', 'DREB_PCT', 'USG_PCT', 'TS_PCT',
       'AST_PCT'],
      dtype='str')

In [ ]:
bio_data_json = json.loads(bio_data.get_json())

In [77]:
bio_data_json.keys()

dict_keys(['resource', 'parameters', 'resultSets'])

In [79]:
bio_data_json['resultSets']

[{'name': 'LeagueDashPlayerBioStats',
  'headers': ['PLAYER_ID',
   'PLAYER_NAME',
   'TEAM_ID',
   'TEAM_ABBREVIATION',
   'AGE',
   'PLAYER_HEIGHT',
   'PLAYER_HEIGHT_INCHES',
   'PLAYER_WEIGHT',
   'COLLEGE',
   'COUNTRY',
   'DRAFT_YEAR',
   'DRAFT_ROUND',
   'DRAFT_NUMBER',
   'GP',
   'PTS',
   'REB',
   'AST',
   'NET_RATING',
   'OREB_PCT',
   'DREB_PCT',
   'USG_PCT',
   'TS_PCT',
   'AST_PCT'],
  'rowSet': [[1630639,
    'A.J. Lawson',
    1610612761,
    'TOR',
    25.0,
    '6-6',
    78,
    '179',
    'South Carolina',
    'Canada',
    'Undrafted',
    'Undrafted',
    'Undrafted',
    14,
    49,
    23,
    3,
    -14.2,
    0.055,
    0.16,
    0.185,
    0.545,
    0.045],
   [1631260,
    'AJ Green',
    1610612749,
    'MIL',
    26.0,
    '6-4',
    76,
    '190',
    'Northern Iowa',
    'USA',
    'Undrafted',
    'Undrafted',
    'Undrafted',
    60,
    589,
    150,
    115,
    -2.0,
    0.009,
    0.073,
    0.128,
    0.611,
    0.086],
   [1642358,
    'AJ Johnson',
    1610612742,
    'DAL',
    21.0,
    '6-5',
    77,
    '160',
    'None',
    'USA',
    '2024',
    '1',
    '23',
    36,
    103,
    43,
    32,
    -4.8,
    0.025,
    0.103,
    0.189,
    0.397,
    0.147],
   [203932,
    'Aaron Gordon',
    1610612743,
    'DEN',
    30.0,
    '6-8',
    80,
    '235',
    'Arizona',
    'USA',
    '2014',
    '1',
    '4',
    25,
    432,
    155,
    64,
    13.5,
    0.052,
    0.162,
    0.227,
    0.622,
    0.132],
   [1628988,
    'Aaron Holiday',
    1610612745,
    'HOU',
    29.0,
    '6-0',
    72,
    '185',
    'UCLA',
    'USA',
    '2018',
    '1',
    '23',
    42,
    231,
    37,
    37,
    4.3,
    0.011,
    0.054,
    0.171,
    0.568,
    0.098],
   [1630174,
    'Aaron Nesmith',
    1610612754,
    'IND',
    26.0,
    '6-5',
    77,
    '215',
    'Vanderbilt',
    'USA',
    '2020',
    '1',
    '14',
    37,
    484,
    165,
    77,
    -5.9,
    0.037,
    0.109,
    0.188,
    0.524,
    0.1],
   [1630598,
    'Aaron Wiggins',
    1610612760,
    'OKC',
    27.0,
    '6-5',
    77,
    '190',
    'Maryland',
    'USA',
    '2021',
    '2',
    '55',
    51,
    519,
    171,
    94,
    8.2,
    0.028,
    0.102,
    0.194,
    0.537,
    0.113],
   [1642846,
    'Ace Bailey',
    1610612762,
    'UTA',
    19.0,
    '6-9',
    81,
    '200',
    'Rutgers',
    'USA',
    '2025',
    '1',
    '5',
    57,
    704,
    229,
    96,
    -10.6,
    0.055,
    0.088,
    0.196,
    0.527,
    0.094],
   [1641737,
    'Adem Bona',
    1610612755,
    'PHI',
    22.0,
    '6-10',
    82,
    '235',
    'UCLA',
    'Nigeria',
    '2024',
    '2',
    '41',
    56,
    258,
    238,
    24,
    -0.2,
    0.099,
    0.136,
    0.105,
    0.634,
    0.033],
   [1642876,
    'Adou Thiero',
    1610612747,
    'LAL',
    21.0,
    '6-7',
    79,
    '220',
    'Arkansas',
    'USA',
    '2025',
    '2',
    '36',
    19,
    28,
    20,
    6,
    -3.5,
    0.07,
    0.143,
    0.12,
    0.551,
    0.08],
   [1642349,
    'Ajay Mitchell',
    1610612760,
    'OKC',
    23.0,
    '6-4',
    76,
    '190',
    'California-Santa Barbara',
    'Belgium',
    '2024',
    '2',
    '38',
    44,
    630,
    151,
    160,
    16.0,
    0.026,
    0.094,
    0.214,
    0.592,
    0.193],
   [201143,
    'Al Horford',
    1610612744,
    'GSW',
    39.0,
    '6-8',
    80,
    '240',
    'Florida',
    'Dominican Republic',
    '2007',
    '1',
    '3',
    42,
    354,
    214,
    112,
    -0.8,
    0.045,
    0.188,
    0.161,
    0.554,
    0.171],
   [1627936,
    'Alex Caruso',
    1610612760,
    'OKC',
    32.0,
    '6-5',
    77,
    '186',
    'Texas A&M',
    'USA',
    'Undrafted',
    'Undrafted',
    'Undrafted',
    43,
    277,
    115,
    86,
    17.5,
    0.029,
    0.107,
    0.154,
    0.544,
    0.142],
   [1642259,
    'Alex Sarr',
    1610612764,
    'WAS',
    20.0,
    '7-0',
    84,
    '205',
    'None',
    'France',
    '2024',
    '1',
    '2',
    43,
    739,
    329,
    117,
    -11.6,
    0.077,
    0.18,
    0.251,
    0.559,
    0.159],
   [1642918,
    'Alijah Martin',
    1610612761,
    'TOR',
    24.0,
    '6-2',
    74,
    '210',
    'Florida',
    'USA',
    '2025',
    '2',
    '39',
    15,
    36,
    14,
    8,
    -3.0,
    0.052,
    0.081,
    0.18,
    0.46,
    0.133],
   [1631214,
    'Alondes Williams',
    1610612764,
    'WAS',
    26.0,
    '6-4',
    76,
    '210',
    'Wake Forest',
    'USA',
    'Undrafted',
    'Undrafted',
    'Undrafted',
    4,
    44,
    25,
    12,
    15.6,
    0.054,
    0.192,
    0.141,
    0.745,
    0.14],
   [1630578,
    'Alperen Sengun',
    1610612745,
    'HOU',
    23.0,
    '6-11',
    83,
    '243',
    'None',
    'Turkey',
    '2021',
    '1',
    '16',
    57,
    1159,
    517,
    348,
    2.9,
    0.089,
    0.177,
    0.265,
    0.554,
    0.28],
   [1642873,
    'Amari Williams',
    1610612738,
    'BOS',
    24.0,
    '6-11',
    83,
    '250',
    'Kentucky',
    'United Kingdom',
    '2025',
    '2',
    '46',
    18,
    22,
    30,
    8,
    -13.6,
    0.051,
    0.17,
    0.096,
    0.517,
    0.107],
   [1641708,
    'Amen Thompson',
    1610612745,
    'HOU',
    23.0,
    '6-7',
    79,
    '200',
    'None',
    'USA',
    '2023',
    '1',
    '4',
    62,
    1099,
    473,
    328,
    6.7,
    0.074,
    0.122,
    0.195,
    0.58,
    0.204],
   [1629599,
    'Amir Coffey',
    1610612756,
    'PHX',
    28.0,
    '6-7',
    79,
    '210',
    'Minnesota',
    'USA',
    'Undrafted',
    'Undrafted',
    'Undrafted',
    40,
    123,
    50,
    22,
    -4.7,
    0.038,
    0.077,
    0.113,
    0.59,
    0.074],
   [203083,
    'Andre Drummond',
    1610612755,
    'PHI',
    32.0,
    '6-11',
    83,
    '279',
    'Connecticut',
    'USA',
    '2012',
    '1',
    '9',
    49,
    319,
    414,
    48,
    -6.8,
    0.148,
    0.272,
    0.145,
    0.548,
    0.074],
   [1641748,
    'Andre Jackson Jr.',
    1610612749,
    'MIL',
    24.0,
    '6-6',
    78,
    '209',
    'Connecticut',
    'USA',
    '2023',
    '2',
    '36',
    34,
    43,
    35,
    27,
    -4.6,
    0.066,
    0.113,
    0.157,
    0.339,
    0.194],
   [1629614,
    'Andrew Nembhard',
    1610612754,
    'IND',
    26.0,
    '6-4',
    76,
    '191',
    'Gonzaga',
    'Canada',
    '2022',
    '2',
    '31',
    50,
    855,
    141,
    368,
    -11.2,
    0.013,
    0.076,
    0.237,
    0.559,
    0.361],
   [203952,
    'Andrew Wiggins',
    1610612748,
    'MIA',
    31.0,
    '6-6',
    78,
    '197',
    'Kansas',
    'Canada',
    '2014',
    '1',
    '1',
    57,
    905,
    291,
    159,
    0.7,
    0.052,
    0.1,
    0.197,
    0.579,
    0.126],
   [1629014,
    'Anfernee Simons',
    1610612741,
    'CHI',
    26.0,
    '6-3',
    75,
    '200',
    'None',
    'USA',
    '2018',
    '1',
    '24',
    55,
    785,
    135,
    134,
    3.0,
    0.021,
    0.075,
    0.227,
    0.576,
    0.151],
   [1641710,
    'Anthony Black',
    1610612753,
    'ORL',
    22.0,
    '6-7',
    79,
    '200',
    'Arkansas',
    'USA',
    '2023',
    '1',
    '6',
    60,
    917,
    232,
    229,
    0.7,
    0.023,
    0.1,
    0.218,
    0.552,
    0.185],
   [203076,
    'Anthony Davis',
    1610612764,
    'WAS',
    33.0,
    '6-10',
    82,
    '253',
    'Kentucky',
    'USA',
    '2012',
    '1',
    '1',
    20,
    407,
    221,
    56,
    -4.6,
    0.099,
    0.24,
    0.272,
    0.551,
    0.14],
   [1630162,
    'Anthony Edwards',
    1610612750,
    'MIN',
    24.0,
    '6-4',
    76,
    '225',
    'Georgia',
    'USA',
    '2020',
    '1',
    '1',
    55,
    1613,
    280,
    201,
    4.1,
    0.017,
    0.121,
    0.308,
    0.618,
    0.17],
   [1630264,
    'Anthony Gill',
    1610612764,
    'WAS',
    33.0,
    '6-7',
    79,
    '230',
    'Virginia',
    'USA',
    'Undrafted',
    'Undrafted',
    'Undrafted',
    37,
    149,
    88,
    34,
    -8.7,
    0.064,
    0.122,
    0.115,
    0.652,
    0.1],
   [1641810,
    'Antonio Reeves',
    1610612766,
    'CHA',
    25.0,
    '6-5',
    77,
    '205',
    'Kentucky',
    'USA',
    '2024',
    '2',
    '47',
    9,
    27,
    8,
    2,
    18.5,
    0.029,
    0.103,
    0.135,
    0.675,
    0.047],
   [1630574,
    'Ariel Hukporti',
    1610612752,
    'NYK',
    23.0,
    '7-0',
    84,
    '246',
    'None',
    'Germany',
    '2024',
    '2',
    '58',
    47,
    88,
    133,
    23,
    1.3,
    0.1,
    0.193,
    0.097,
    0.608,
    0.076],
   [1642854,
    'Asa Newell',
    1610612737,
    'ATL',
    20.0,
    '6-10',
    82,
    '220',
    'Georgia',
    'USA',
    '2025',
    '1',
    '23',
    40,
    201,
    81,
    20,
    -2.8,
    0.074,
    0.1,
    0.159,
    0.628,
    0.063],
   [1641709,
    'Ausar Thompson',
    1610612765,
    'DET',
    23.0,
    '6-7',
    79,
    '205',
    'None',
    'USA',
    '2023',
    '1',
    '5',
    57,
    581,
    334,
    167,
    10.0,
    0.081,
    0.139,
    0.172,
    0.545,
    0.151],
   [1630559,
    'Austin Reaves',
    1610612747,
    'LAL',
    27.0,
    '6-5',
    77,
    '197',
    'Oklahoma',
    'USA',
    'Undrafted',
    'Undrafted',
    'Undrafted',
    39,
    924,
    186,
    213,
    3.7,
    0.021,
    0.122,
    0.266,
    0.651,
    0.248],
   [1630245,
    'Ayo Dosunmu',
    1610612750,
    'MIN',
    26.0,
    '6-4',
    76,
    '201',
    'Illinois',
    'USA',
    '2021',
    '2',
    '38',
    57,
    809,
    159,
    194,
    -4.1,
    0.023,
    0.076,
    0.196,
    0.629,
    0.2],
   [1628389,
    'Bam Adebayo',
    1610612748,
    'MIA',
    28.0,
    '6-9',
    81,
    '255',
    'Kentucky',
    'USA',
    '2017',
    '1',
    '14',
    58,
    1161,
    569,
    169,
    8.0,
    0.06,
    0.232,
    0.249,
    0.555,
    0.135],
   [1631248,
    'Baylor Scheierman',
    1610612738,
    'BOS',
    25.0,
    '6-6',
    78,
    '205',
    'Creighton',
    'USA',
    '2024',
    '1',
    '30',
    60,
    287,
    194,
    74,
    8.8,
    0.034,
    0.145,
    0.112,
    0.616,
    0.098],
   [1642879,
    'Ben Saraf',
    1610612751,
    'BKN',
    19.0,
    '6-6',
    78,
    '200',
    'None',
    'Israel',
    '2025',
    '1',
    '26',
    29,
    149,
    43,
    85,
    -10.7,
    0.016,
    0.074,
    0.178,
    0.463,
    0.241],
   [1641767,
    'Ben Sheppard',
    1610612754,
    'IND',
    24.0,
    '6-6',
    78,
    '190',
    'Belmont',
    'USA',
    '2023',
    '1',
    '26',
    54,
    373,
    166,
    99,
    -10.3,
    0.025,
    0.111,
    0.129,
    0.542,
    0.117],
   [1631097,
    'Bennedict Mathurin',
    1610612746,
    'LAC',
    23.0,
    '6-5',
    77,
    '210',
    'Arizona',
    'Canada',
    '2022',
    '1',
    '6',
    40,
    727,
    228,
    91,
    -4.6,
    0.031,
    0.144,
    0.245,
    0.571,
    0.115],
   [1641731,
    'Bilal Coulibaly',
    1610612764,
    'WAS',
    21.0,
    '6-7',
    79,
    '195',
    'None',
    'France',
    '2023',
    '1',
    '7',
    44,
    457,
    191,
    114,
    -11.0,
    0.029,
    0.127,
    0.179,
    0.514,
    0.133],
   [202687,
    'Bismack Biyombo',
    1610612759,
    'SAS',
    33.0,
    '6-8',
    80,
    '255',
    'None',
    'DRC',
    '2011',
    '1',
    '7',
    19,
    16,
    16,
    5,
    -23.8,
    0.041,
    0.121,
    0.069,
    0.714,
    0.068],
   [1642396,
    'Blake Hinson',
    1610612762,
    'UTA',
    26.0,
    '6-8',
    80,
    '230',
    'Pittsburgh',
    'USA',
    'Undrafted',
    'Undrafted',
    'Undrafted',
    8,
    75,
    19,
    6,
    -4.5,
    0.039,
    0.067,
    0.148,
    0.649,
    0.056],
   [1631104,
    'Blake Wesley',
    1610612757,
    'POR',
    22.0,
    '6-4',
    76,
    '190',
    'Notre Dame',
    'USA',
    '2022',
    '1',
    '25',
    21,
    116,
    29,
    53,
    -10.9,
    0.021,
    0.078,
    0.179,
    0.515,
    0.26],
   [1626171,
    'Bobby Portis',
    1610612749,
    'MIL',
    31.0,
    '6-9',
    81,
    '250',
    'Arkansas',
    'USA',
    '2015',
    '1',
    '22',
    61,
    812,
    386,
    94,
    -7.5,
    0.055,
    0.196,
    0.219,
    0.595,
    0.102],
   [1641752,
    'Bobi Klintman',
    1610612765,
    'DET',
    23.0,
    '6-9',
    81,
    '225',
    'None',
    'Sweden',
    '2024',
    '2',
    '37',
    11,
    20,
    18,
    6,
    -3.9,
    0.058,
    0.178,
    0.182,
    0.366,
    0.13],
   [203992,
    'Bogdan Bogdanović',
    1610612746,
    'LAC',
    33.0,
    '6-5',
    77,
    '225',
    'None',
    'Serbia',
    '2014',
    '1',
    '27',
    18,
    138,
    53,
    48,
    -4.6,
    0.016,
    0.113,
    0.183,
    0.5,
    0.201],
   [1630538,
    'Bones Hyland',
    1610612750,
    'MIN',
    25.0,
    '6-2',
    74,
    '169',
    'Virginia Commonwealth',
    'USA',
    '2021',
    '1',
    '26',
    56,
    401,
    94,
    142,
    3.5,
    0.022,
    0.088,
    0.187,
    0.592,
    0.231],
   [203078,
    'Bradley Beal',
    1610612746,
    'LAC',
    32.0,
    '6-4',
    76,
    '207',
    'Florida',
    'USA',
    '2012',
    '1',
    '3',
    6,
    49,
    5,
    10,
    -9.3,
    0.019,
    0.025,
    0.224,
    0.476,
    0.106],
   [1642382,
    'Branden Carlson',
    1610612760,
    'OKC',
    26.0,
    '7-0',
    84,
    '220',
    'Utah',
    'USA',
    'Undrafted',
    'Undrafted',
    'Undrafted',
    35,
    170,
    92,
    21,
    3.8,
    0.063,
    0.165,
    0.176,
    0.601,
    0.08],
   [1641764,
    'Brandin Podziemski',
    1610612744,
    'GSW',
    23.0,
    '6-4',
    76,
    '205',
    'Santa Clara',
    'USA',
    '2023',
    '1',
    '19',
    65,
    822,
    336,
    245,
    0.6,
    0.03,
    0.148,
    0.189,
    0.564,
    0.202],
   [1629634,
    'Brandon Clarke',
    1610612763,
    'MEM',
    29.0,
    '6-8',
    80,
    '215',
    'Gonzaga',
    'Canada',
    '2019',
    '1',
    '21',
    2,
    8,
    6,
    1,
    -22.2,
    0.154,
    0.077,
    0.193,
    0.372,
    0.071],
   [1627742,
    'Brandon Ingram',
    1610612761,
    'TOR',
    28.0,
    '6-8',
    80,
    '190',
    'Duke',
    'USA',
    '2016',
    '1',
    '2',
    62,
    1333,
    353,
    236,
    0.4,
    0.023,
    0.145,
    0.267,
    0.562,
    0.175],
   [1641706,
    'Brandon Miller',
    1610612766,
    'CHA',
    23.0,
    '6-7',
    79,
    '200',
    'Alabama',
    'USA',
    '2023',
    '1',
    '2',
    49,
    1014,
    251,
    166,
    5.9,
    0.036,
    0.127,
    0.285,
    0.57,
    0.182],
   [1630314,
    'Brandon Williams',
    1610612742,
    'DAL',
    26.0,
    '6-1',
    73,
    '190',
    'Arizona',
    'USA',
    'Undrafted',
    'Undrafted',
    'Undrafted',
    56,
    733,
    163,
    212,
    -2.0,
    0.02,
    0.104,
    0.246,
    0.568,
    0.249],
   [1641729,
    'Brice Sensabaugh',
    1610612762,
    'UTA',
    22.0,
    '6-6',
    78,
    '235',
    'Ohio State',
    'USA',
    '2023',
    '1',
    '28',
    62,
    797,
    183,
    101,
    -6.8,
    0.032,
    0.096,
    0.228,
    0.571,
    0.11],
   [1642355,
    'Bronny James',
    1610612747,
    'LAL',
    21.0,
    '6-2',
    74,
    '210',
    'Southern California',
    'USA',
    '2024',
    '2',
    '55',
    32,
    66,
    15,
    38,
    -7.5,
    0.019,
    0.053,
    0.149,
    0.506,
    0.236],
   [201572,
    'Brook Lopez',
    1610612746,
    'LAC',
    37.0,
    '7-1',
    85,
    '282',
    'Stanford',
    'USA',
    '2008',
    '1',
    '10',
    57,
    447,
    175,
    64,
    1.5,
    0.024,
    0.128,
    0.176,
    0.547,
    0.085],
   [1642964,
    'Brooks Barnhizer',
    1610612760,
    'OKC',
    24.0,
    '6-5',
    77,
    '230',
    'Northwestern',
    'USA',
    '2025',
    '2',
    '44',
    33,
    47,
    57,
    18,
    -10.5,
    0.041,
    0.162,
    0.1,
    0.446,
    0.105],
   [1628971,
    'Bruce Brown',
    1610612743,
    'DEN',
    29.0,
    '6-4',
    76,
    '202',
    'Miami',
    'USA',
    '2018',
    '2',
    '42',
    65,
    490,
    258,
    141,
    -2.6,
    0.047,
    0.106,
    0.136,
    0.543,
    0.121],
   [1631121,
    'Bryce McGowens',
    1610612740,
    'NOP',
    23.0,
    '6-6',
    78,
    '190',
    'Nebraska',
    'USA',
    '2022',
    '2',
    '40',
    42,
    340,
    88,
    62,
    -3.6,
    0.013,
    0.082,
    0.136,
    0.61,
    0.091],
   [1642267,
    'Bub Carrington',
    1610612764,
    'WAS',
    20.0,
    '6-4',
    76,
    '190',
    'Pittsburgh',
    'USA',
    '2024',
    '1',
    '14',
    64,
    630,
    233,
    292,
    -14.9,
    0.015,
    0.111,
    0.168,
    0.534,
    0.226],
   [1631205,
    'Buddy Boeheim',
    1610612760,
    'OKC',
    26.0,
    '6-5',
    77,
    '205',
    'Syracuse',
    'USA',
    'Undrafted',
    'Undrafted',
    'Undrafted',
    4,
    6,
    0,
    0,
    12.0,
    0.0,
    0.0,
    0.158,
    0.5,
    0.0],
   [1627741,
    'Buddy Hield',
    1610612737,
    'ATL',
    33.0,
    '6-4',
    76,
    '220',
    'Oklahoma',
    'Bahamas',
    '2016',
    '1',
    '6',
    45,
    354,
    108,
    66,
    -5.3,
    0.032,
    0.104,
    0.188,
    0.56,
    0.129],
   [203468,
    'CJ McCollum',
    1610612737,
    'ATL',
    34.0,
    '6-3',
    75,
    '190',
    'Lehigh',
    'USA',
    '2013',
    '1',
    '10',
    60,
    1116,
    209,
    221,
    -2.0,
    0.024,
    0.081,
    0.245,
    0.564,
    0.185],
   [1630595,
    'Cade Cunningham',
    1610612765,
    'DET',
    24.0,
    '6-6',
    78,
    '220',
    'Oklahoma State',
    'USA',
    '2021',
    '1',
    '1',
    57,
    1433,
    322,
    566,
    10.5,
    0.025,
    0.131,
    0.3,
    0.564,
    0.426],
   [1631216,
    'Caleb Houstan',
    1610612737,
    'ATL',
    23.0,
    '6-8',
    80,
    '205',
    'Michigan',
    'Canada',
    '2022',
    '2',
    '32',
    12,
    23,
    6,
    2,
    -5.9,
    0.074,
    0.041,
    0.156,
    0.705,
    0.063],
   [1631126,
    'Caleb Love',
    1610612757,
    'POR',
    24.0,
    '6-3',
    75,
    '212',
    'Arizona',
    'USA',
    'Undrafted',
    'Undrafted',
    'Undrafted',
    45,
    507,
    114,
    122,
    -5.9,
    0.023,
    0.085,
    0.228,
    0.5,
    0.187],
   [1628997,
    'Caleb Martin',
    1610612742,
    'DAL',
    30.0,
    '6-5',
    77,
    '205',
    'Nevada',
    'USA',
    'Undrafted',
    'Undrafted',
    'Undrafted',
    55,
    216,
    138,
    78,
    -7.9,
    0.029,
    0.128,
    0.12,
    0.529,
    0.131],
   [1642353,
    'Cam Christie',
    1610612746,
    'LAC',
    20.0,
    '6-5',
    77,
    '190',
    'Minnesota',
    'USA',
    '2024',
    '2',
    '46',
    43,
    133,
    64,
    25,
    -0.8,
    0.037,
    0.114,
    0.168,
    0.491,
    0.095],
   [1642285,
    'Cam Spencer',
    1610612763,
    'MEM',
    25.0,
    '6-3',
    75,
    '205',
    'Connecticut',
    'USA',
    '2024',
    '2',
    '53',
    62,
    701,
    165,
    340,
    -2.4,
    0.021,
    0.087,
    0.167,
    0.653,
    0.324],
   [1630560,
    'Cam Thomas',
    1610612749,
    'MIL',
    24.0,
    '6-3',
    75,
    '210',
    'Louisiana State',
    'Japan',
    '2021',
    '1',
    '27',
    38,
    543,
    67,
    103,
    -11.2,
    0.013,
    0.072,
    0.297,
    0.534,
    0.211],
   [1641715,
    'Cam Whitmore',
    1610612764,
    'WAS',
    21.0,
    '6-6',
    78,
    '230',
    'Villanova',
    'USA',
    '2023',
    '1',
    '20',
    21,
    193,
    58,
    15,
    -19.6,
    0.049,
    0.102,
    0.225,
    0.528,
    0.067],
   [1629661,
    'Cameron Johnson',
    1610612743,
    'DEN',
    30.0,
    '6-8',
    80,
    '210',
    'North Carolina',
    'USA',
    '2019',
    '1',
    '11',
    39,
    432,
    146,
    91,
    7.8,
    0.026,
    0.095,
    0.141,
    0.59,
    0.093],
   [1626166,
    'Cameron Payne',
    1610612755,
    'PHI',
    31.0,
    '6-2',
    74,
    '183',
    'Murray State',
    'USA',
    '2015',
    '1',
    '14',
    11,
    76,

In [ ]:

import pandas as pd
from datetime import datetime
import time

def get_current_season():
    current_date = datetime.now()
    current_year = current_date.year
    current_month = current_date.month

    if current_month > 4:
        return f"{current_year}-{str(current_year + 1)[-2:]}"
    else:
        return f"{current_year - 1}-{str(current_year)[-2:]}"
    
def get_prev_n_seasons(current_season, n):
    seasons = []
    start_year = int(current_season.split('-')[0])
    for i in range(n):
        previous_start_year = start_year - (i + 1)
        previous_end_year = start_year - i
        seasons.append(f"{previous_start_year}-{str(previous_end_year)[-2:]}")
    return seasons

bio_ingest_df = pd.DataFrame()
current_season = get_current_season()
for season in [current_season] + get_prev_n_seasons(current_season, 5):
    bio_data = leaguedashplayerbiostats.LeagueDashPlayerBioStats(season=season)
    bio_df = bio_data.get_data_frames()[0][["PLAYER_ID", "PLAYER_NAME", "AGE", "PLAYER_HEIGHT_INCHES", "PLAYER_WEIGHT"]]
    bio_df["SEASON"] = season
    bio_ingest_df = pd.concat([bio_ingest_df, bio_df], ignore_index=True)
    time.sleep(0.5)  # Sleep for 1 second to avoid hitting rate limits

bio_json = bio_ingest_df.to_json(orient='records', lines=True)

In [102]:
bio_ingest_df['SEASON'].value_counts()

SEASON
2021-22    605
2023-24    572
2024-25    569
2025-26    551
2020-21    540
2022-23    539
Name: count, dtype: int64

In [103]:
bio_ingest_df[bio_ingest_df['PLAYER_NAME'] == 'Aaron Gordon']

      PLAYER_ID   PLAYER_NAME   AGE  PLAYER_HEIGHT_INCHES   SEASON
3        203932  Aaron Gordon  30.0                    80  2025-26
554      203932  Aaron Gordon  29.0                    80  2024-25
1123     203932  Aaron Gordon  28.0                    80  2023-24
1695     203932  Aaron Gordon  27.0                    80  2022-23
2231     203932  Aaron Gordon  26.0                    80  2021-22
2836     203932  Aaron Gordon  25.0                    80  2020-21

In [104]:
bio_json

'{"PLAYER_ID":1630639,"PLAYER_NAME":"A.J. Lawson","AGE":25.0,"PLAYER_HEIGHT_INCHES":78,"SEASON":"2025-26"}\n{"PLAYER_ID":1631260,"PLAYER_NAME":"AJ Green","AGE":26.0,"PLAYER_HEIGHT_INCHES":76,"SEASON":"2025-26"}\n{"PLAYER_ID":1642358,"PLAYER_NAME":"AJ Johnson","AGE":21.0,"PLAYER_HEIGHT_INCHES":77,"SEASON":"2025-26"}\n{"PLAYER_ID":203932,"PLAYER_NAME":"Aaron Gordon","AGE":30.0,"PLAYER_HEIGHT_INCHES":80,"SEASON":"2025-26"}\n{"PLAYER_ID":1628988,"PLAYER_NAME":"Aaron Holiday","AGE":29.0,"PLAYER_HEIGHT_INCHES":72,"SEASON":"2025-26"}\n{"PLAYER_ID":1630174,"PLAYER_NAME":"Aaron Nesmith","AGE":26.0,"PLAYER_HEIGHT_INCHES":77,"SEASON":"2025-26"}\n{"PLAYER_ID":1630598,"PLAYER_NAME":"Aaron Wiggins","AGE":27.0,"PLAYER_HEIGHT_INCHES":77,"SEASON":"2025-26"}\n{"PLAYER_ID":1642846,"PLAYER_NAME":"Ace Bailey","AGE":19.0,"PLAYER_HEIGHT_INCHES":81,"SEASON":"2025-26"}\n{"PLAYER_ID":1641737,"PLAYER_NAME":"Adem Bona","AGE":22.0,"PLAYER_HEIGHT_INCHES":82,"SEASON":"2025-26"}\n{"PLAYER_ID":1642876,"PLAYER_NAME":"Adou Thiero","AGE":21.0,"PLAYER_HEIGHT_INCHES":79,"SEASON":"2025-26"}\n{"PLAYER_ID":1642349,"PLAYER_NAME":"Ajay Mitchell","AGE":23.0,"PLAYER_HEIGHT_INCHES":76,"SEASON":"2025-26"}\n{"PLAYER_ID":201143,"PLAYER_NAME":"Al Horford","AGE":39.0,"PLAYER_HEIGHT_INCHES":80,"SEASON":"2025-26"}\n{"PLAYER_ID":1627936,"PLAYER_NAME":"Alex Caruso","AGE":32.0,"PLAYER_HEIGHT_INCHES":77,"SEASON":"2025-26"}\n{"PLAYER_ID":1642259,"PLAYER_NAME":"Alex Sarr","AGE":20.0,"PLAYER_HEIGHT_INCHES":84,"SEASON":"2025-26"}\n{"PLAYER_ID":1642918,"PLAYER_NAME":"Alijah Martin","AGE":24.0,"PLAYER_HEIGHT_INCHES":74,"SEASON":"2025-26"}\n{"PLAYER_ID":1631214,"PLAYER_NAME":"Alondes Williams","AGE":26.0,"PLAYER_HEIGHT_INCHES":76,"SEASON":"2025-26"}\n{"PLAYER_ID":1630578,"PLAYER_NAME":"Alperen Sengun","AGE":23.0,"PLAYER_HEIGHT_INCHES":83,"SEASON":"2025-26"}\n{"PLAYER_ID":1642873,"PLAYER_NAME":"Amari Williams","AGE":24.0,"PLAYER_HEIGHT_INCHES":83,"SEASON":"2025-26"}\n{"PLAYER_ID":1641708,"PLAYER_NAME":"Amen Thompson","AGE":23.0,"PLAYER_HEIGHT_INCHES":79,"SEASON":"2025-26"}\n{"PLAYER_ID":1629599,"PLAYER_NAME":"Amir Coffey","AGE":28.0,"PLAYER_HEIGHT_INCHES":79,"SEASON":"2025-26"}\n{"PLAYER_ID":203083,"PLAYER_NAME":"Andre Drummond","AGE":32.0,"PLAYER_HEIGHT_INCHES":83,"SEASON":"2025-26"}\n{"PLAYER_ID":1641748,"PLAYER_NAME":"Andre Jackson Jr.","AGE":24.0,"PLAYER_HEIGHT_INCHES":78,"SEASON":"2025-26"}\n{"PLAYER_ID":1629614,"PLAYER_NAME":"Andrew Nembhard","AGE":26.0,"PLAYER_HEIGHT_INCHES":76,"SEASON":"2025-26"}\n{"PLAYER_ID":203952,"PLAYER_NAME":"Andrew Wiggins","AGE":31.0,"PLAYER_HEIGHT_INCHES":78,"SEASON":"2025-26"}\n{"PLAYER_ID":1629014,"PLAYER_NAME":"Anfernee Simons","AGE":26.0,"PLAYER_HEIGHT_INCHES":75,"SEASON":"2025-26"}\n{"PLAYER_ID":1641710,"PLAYER_NAME":"Anthony Black","AGE":22.0,"PLAYER_HEIGHT_INCHES":79,"SEASON":"2025-26"}\n{"PLAYER_ID":203076,"PLAYER_NAME":"Anthony Davis","AGE":33.0,"PLAYER_HEIGHT_INCHES":82,"SEASON":"2025-26"}\n{"PLAYER_ID":1630162,"PLAYER_NAME":"Anthony Edwards","AGE":24.0,"PLAYER_HEIGHT_INCHES":76,"SEASON":"2025-26"}\n{"PLAYER_ID":1630264,"PLAYER_NAME":"Anthony Gill","AGE":33.0,"PLAYER_HEIGHT_INCHES":79,"SEASON":"2025-26"}\n{"PLAYER_ID":1641810,"PLAYER_NAME":"Antonio Reeves","AGE":25.0,"PLAYER_HEIGHT_INCHES":77,"SEASON":"2025-26"}\n{"PLAYER_ID":1630574,"PLAYER_NAME":"Ariel Hukporti","AGE":23.0,"PLAYER_HEIGHT_INCHES":84,"SEASON":"2025-26"}\n{"PLAYER_ID":1642854,"PLAYER_NAME":"Asa Newell","AGE":20.0,"PLAYER_HEIGHT_INCHES":82,"SEASON":"2025-26"}\n{"PLAYER_ID":1641709,"PLAYER_NAME":"Ausar Thompson","AGE":23.0,"PLAYER_HEIGHT_INCHES":79,"SEASON":"2025-26"}\n{"PLAYER_ID":1630559,"PLAYER_NAME":"Austin Reaves","AGE":27.0,"PLAYER_HEIGHT_INCHES":77,"SEASON":"2025-26"}\n{"PLAYER_ID":1630245,"PLAYER_NAME":"Ayo Dosunmu","AGE":26.0,"PLAYER_HEIGHT_INCHES":76,"SEASON":"2025-26"}\n{"PLAYER_ID":1628389,"PLAYER_NAME":"Bam Adebayo","AGE":28.0,"PLAYER_HEIGHT_INCHES":81,"SEASON":"2025-26"}\n{"PLAYER_ID":1631248,"PLAYER_NAME":"Baylor Scheierman","AGE":25.0,"PLAYER_HEIGHT_INCHES":78,"SEASON":"2025-26"}\n{"PLAYER_ID":1642879,"PLAYER_NAME":"Ben Saraf","AGE":19.0,"PLAYER_HEIGHT_INCHES":78,"SEASON":"2025-26"}\n{"PLAYER_ID":1641767,"PLAYER_NAME":"Ben Sheppard","AGE":24.0,"PLAYER_HEIGHT_INCHES":78,"SEASON":"2025-26"}\n{"PLAYER_ID":1631097,"PLAYER_NAME":"Bennedict Mathurin","AGE":23.0,"PLAYER_HEIGHT_INCHES":77,"SEASON":"2025-26"}\n{"PLAYER_ID":1641731,"PLAYER_NAME":"Bilal Coulibaly","AGE":21.0,"PLAYER_HEIGHT_INCHES":79,"SEASON":"2025-26"}\n{"PLAYER_ID":202687,"PLAYER_NAME":"Bismack Biyombo","AGE":33.0,"PLAYER_HEIGHT_INCHES":80,"SEASON":"2025-26"}\n{"PLAYER_ID":1642396,"PLAYER_NAME":"Blake Hinson","AGE":26.0,"PLAYER_HEIGHT_INCHES":80,"SEASON":"2025-26"}\n{"PLAYER_ID":1631104,"PLAYER_NAME":"Blake Wesley","AGE":22.0,"PLAYER_HEIGHT_INCHES":76,"SEASON":"2025-26"}\n{"PLAYER_ID":1626171,"PLAYER_NAME":"Bobby Portis","AGE":31.0,"PLAYER_HEIGHT_INCHES":81,"SEASON":"2025-26"}\n{"PLAYER_ID":1641752,"PLAYER_NAME":"Bobi Klintman","AGE":23.0,"PLAYER_HEIGHT_INCHES":81,"SEASON":"2025-26"}\n{"PLAYER_ID":203992,"PLAYER_NAME":"Bogdan Bogdanovi\\u0107","AGE":33.0,"PLAYER_HEIGHT_INCHES":77,"SEASON":"2025-26"}\n{"PLAYER_ID":1630538,"PLAYER_NAME":"Bones Hyland","AGE":25.0,"PLAYER_HEIGHT_INCHES":74,"SEASON":"2025-26"}\n{"PLAYER_ID":203078,"PLAYER_NAME":"Bradley Beal","AGE":32.0,"PLAYER_HEIGHT_INCHES":76,"SEASON":"2025-26"}\n{"PLAYER_ID":1642382,"PLAYER_NAME":"Branden Carlson","AGE":26.0,"PLAYER_HEIGHT_INCHES":84,"SEASON":"2025-26"}\n{"PLAYER_ID":1641764,"PLAYER_NAME":"Brandin Podziemski","AGE":23.0,"PLAYER_HEIGHT_INCHES":76,"SEASON":"2025-26"}\n{"PLAYER_ID":1629634,"PLAYER_NAME":"Brandon Clarke","AGE":29.0,"PLAYER_HEIGHT_INCHES":80,"SEASON":"2025-26"}\n{"PLAYER_ID":1627742,"PLAYER_NAME":"Brandon Ingram","AGE":28.0,"PLAYER_HEIGHT_INCHES":80,"SEASON":"2025-26"}\n{"PLAYER_ID":1641706,"PLAYER_NAME":"Brandon Miller","AGE":23.0,"PLAYER_HEIGHT_INCHES":79,"SEASON":"2025-26"}\n{"PLAYER_ID":1630314,"PLAYER_NAME":"Brandon Williams","AGE":26.0,"PLAYER_HEIGHT_INCHES":73,"SEASON":"2025-26"}\n{"PLAYER_ID":1641729,"PLAYER_NAME":"Brice Sensabaugh","AGE":22.0,"PLAYER_HEIGHT_INCHES":78,"SEASON":"2025-26"}\n{"PLAYER_ID":1642355,"PLAYER_NAME":"Bronny James","AGE":21.0,"PLAYER_HEIGHT_INCHES":74,"SEASON":"2025-26"}\n{"PLAYER_ID":201572,"PLAYER_NAME":"Brook Lopez","AGE":37.0,"PLAYER_HEIGHT_INCHES":85,"SEASON":"2025-26"}\n{"PLAYER_ID":1642964,"PLAYER_NAME":"Brooks Barnhizer","AGE":24.0,"PLAYER_HEIGHT_INCHES":77,"SEASON":"2025-26"}\n{"PLAYER_ID":1628971,"PLAYER_NAME":"Bruce Brown","AGE":29.0,"PLAYER_HEIGHT_INCHES":76,"SEASON":"2025-26"}\n{"PLAYER_ID":1631121,"PLAYER_NAME":"Bryce McGowens","AGE":23.0,"PLAYER_HEIGHT_INCHES":78,"SEASON":"2025-26"}\n{"PLAYER_ID":1642267,"PLAYER_NAME":"Bub Carrington","AGE":20.0,"PLAYER_HEIGHT_INCHES":76,"SEASON":"2025-26"}\n{"PLAYER_ID":1631205,"PLAYER_NAME":"Buddy Boeheim","AGE":26.0,"PLAYER_HEIGHT_INCHES":77,"SEASON":"2025-26"}\n{"PLAYER_ID":1627741,"PLAYER_NAME":"Buddy Hield","AGE":33.0,"PLAYER_HEIGHT_INCHES":76,"SEASON":"2025-26"}\n{"PLAYER_ID":203468,"PLAYER_NAME":"CJ McCollum","AGE":34.0,"PLAYER_HEIGHT_INCHES":75,"SEASON":"2025-26"}\n{"PLAYER_ID":1630595,"PLAYER_NAME":"Cade Cunningham","AGE":24.0,"PLAYER_HEIGHT_INCHES":78,"SEASON":"2025-26"}\n{"PLAYER_ID":1631216,"PLAYER_NAME":"Caleb Houstan","AGE":23.0,"PLAYER_HEIGHT_INCHES":80,"SEASON":"2025-26"}\n{"PLAYER_ID":1631126,"PLAYER_NAME":"Caleb Love","AGE":24.0,"PLAYER_HEIGHT_INCHES":75,"SEASON":"2025-26"}\n{"PLAYER_ID":1628997,"PLAYER_NAME":"Caleb Martin","AGE":30.0,"PLAYER_HEIGHT_INCHES":77,"SEASON":"2025-26"}\n{"PLAYER_ID":1642353,"PLAYER_NAME":"Cam Christie","AGE":20.0,"PLAYER_HEIGHT_INCHES":77,"SEASON":"2025-26"}\n{"PLAYER_ID":1642285,"PLAYER_NAME":"Cam Spencer","AGE":25.0,"PLAYER_HEIGHT_INCHES":75,"SEASON":"2025-26"}\n{"PLAYER_ID":1630560,"PLAYER_NAME":"Cam Thomas","AGE":24.0,"PLAYER_HEIGHT_INCHES":75,"SEASON":"2025-26"}\n{"PLAYER_ID":1641715,"PLAYER_NAME":"Cam Whitmore","AGE":21.0,"PLAYER_HEIGHT_INCHES":78,"SEASON":"2025-26"}\n{"PLAYER_ID":1629661,"PLAYER_NAME":"Cameron Johnson","AGE":30.0,"PLAYER_HEIGHT_INCHES":80,"SEASON":"2025-26"}\n{"PLAYER_ID":1626166,"PLAYER_NAME":"Cameron Payne","AGE":31.0,"PLAYER_HEIGHT_INCHES":74,"SEASON":"2025-26"}\n{"PLAYER_ID":1627747,"PLAYER_NAME":"Caris LeVert","AGE":31.0,"PLAYER_HEIGHT_INCHES":79,"SEASON":"2025-26"}\n{"PLAYER_ID":1642868,"PLAYER_NAME":"Carter Bryant","AGE":20.0,"PLAYER_HEIGHT_INCHES":78,"SEASON":"2025-26"}\n{"PLAYER_ID":1641717,"PLAYER_NAME":"Cason Wallace","AGE":22.0,"PLAYER_HEIGHT_INCHES":75,"SEASON":"2025-26"}\n{"PLAYER_ID":1642907,"PLAYER_NAME":"Cedric Coward","AGE":22.0,"PLAYER_HEIGHT_INCHES":77,"SEASON":"2025-26"}\n{"PLAYER_ID":1643052,"PLAYER_NAME":"Chaney Johnson","AGE":23.0,"PLAYER_HEIGHT_INCHES":79,"SEASON":"2025-26"}\n{"PLAYER_ID":1629646,"PLAYER_NAME":"Charles Bassey","AGE":25.0,"PLAYER_HEIGHT_INCHES":82,"SEASON":"2025-26"}\n{"PLAYER_ID":1642404,"PLAYER_NAME":"Chaz Lanier","AGE":24.0,"PLAYER_HEIGHT_INCHES":75,"SEASON":"2025-26"}\n{"PLAYER_ID":1631096,"PLAYER_NAME":"Chet Holmgren","AGE":23.0,"PLAYER_HEIGHT_INCHES":85,"SEASON":"2025-26"}\n{"PLAYER_ID":1628449,"PLAYER_NAME":"Chris Boucher","AGE":33.0,"PLAYER_HEIGHT_INCHES":80,"SEASON":"2025-26"}\n{"PLAYER_ID":1641753,"PLAYER_NAME":"Chris Livingston","AGE":22.0,"PLAYER_HEIGHT_INCHES":78,"SEASON":"2025-26"}\n{"PLAYER_ID":1643024,"PLAYER_NAME":"Chris Ma\\u00f1on","AGE":24.0,"PLAYER_HEIGHT_INCHES":76,"SEASON":"2025-26"}\n{"PLAYER_ID":101108,"PLAYER_NAME":"Chris Paul","AGE":40.0,"PLAYER_HEIGHT_INCHES":72,"SEASON":"2025-26"}\n{"PLAYER_ID":1642959,"PLAYER_NAME":"Chris Youngblood","AGE":24.0,"PLAYER_HEIGHT_INCHES":76,"SEASON":"2025-26"}\n{"PLAYER_ID":1631128,"PLAYER_NAME":"Christian Braun","AGE":24.0,"PLAYER_HEIGHT_INCHES":78,"SEASON":"2025-26"}\n{"PLAYER_ID":1631132,"PLAYER_NAME":"Christian Koloko","AGE":25.0,"PLAYER_HEIGHT_INCHES":83,"SEASON":"2025-26"}\n{"PLAYER_ID":1642935,"PLAYER_NAME":"Chucky Hepburn","AGE":23.0,"PLAYER_HEIGHT_INCHES":72,"SEASON":"2025-26"}\n{"PLAYER_ID":203991,"PLAYER_NAME":"Clint Capela","AGE":31.0,"PLAYER_HEIGHT_INCHES":82,"SEASON":"2025-26"}\n{"PLAYER_ID":1629632,"PLAYER_NAME":"Coby White","AGE":26.0,"PLAYER_HEIGHT_INCHES":76,"SEASON":"2025-26"}\n{"PLAYER_ID":1628998,"PLAYER_NAME":"Cody Martin","AGE":30.0,"PLAYER_HEIGHT_INCHES":78,"SEASON":"2025-26"}\n{"PLAYER_ID":1642262,"PLAYER_NAME":"Cody Williams","AGE":21.0,"PLAYER_HEIGHT_INCHES":80,"SEASON":"2025-26"}\n{"PLAYER_ID":1641732,"PLAYER_NAME":"Colby Jones","AGE":23.0,"PLAYER_HEIGHT_INCHES":78,"SEASON":"2025-26"}\n{"PLAYER_ID":1630175,"PLAYER_NAME":"Cole Anthony","AGE":25.0,"PLAYER_HEIGHT_INCHES":74,"SEASON":"2025-26"}\n{"PLAYER_ID":1631221,"PLAYER_NAME":"Collin Gillespie","AGE":26.0,"PLAYER_HEIGHT_INCHES":73,"SEASON":"2025-26"}\n{"PLAYER_ID":1642867,"PLAYER_NAME":"Collin Murray-Boyles","AGE":20.0,"PLAYER_HEIGHT_INCHES":79,"SEASON":"2025-26"}\n{"PLAYER_ID":1629012,"PLAYER_NAME":"Collin Sexton","AGE":27.0,"PLAYER_HEIGHT_INCHES":75,"SEASON":"2025-26"}\n{"PLAYER_ID":1642843,"PLAYER_NAME":"Cooper Flagg","AGE":19.0,"PLAYER_HEIGHT_INCHES":81,"SEASON":"2025-26"}\n{"PLAYER_ID":1630557,"PLAYER_NAME":"Corey Kispert","AGE":27.0,"PLAYER_HEIGHT_INCHES":78,"SEASON":"2025-26"}\n{"PLAYER_ID":1641854,"PLAYER_NAME":"Craig Porter Jr.","AGE":26.0,"PLAYER_HEIGHT_INCHES":73,"SEASON":"2025-26"}\n{"PLAYER_ID":1642938,"PLAYER_NAME":"Curtis Jones","AGE":24.0,"PLAYER_HEIGHT_INCHES":75,"SEASON":"2025-26"}\n{"PLAYER_ID":1626156,"PLAYER_NAME":"D\'Angelo Russell","AGE":30.0,"PLAYER_HEIGHT_INCHES":75,"SEASON":"2025-26"}\n{"PLAYER_ID":1641747,"PLAYER_NAME":"DaRon Holmes II","AGE":23.0,"PLAYER_HEIGHT_INCHES":81,"SEASON":"2025-26"}\n{"PLAYER_ID":1631342,"PLAYER_NAME":"Daeqwon Plowden","AGE":27.0,"PLAYER_HEIGHT_INCHES":76,"SEASON":"2025-26"}\n{"PLAYER_ID":1630625,"PLAYER_NAME":"Dalano Banton","AGE":26.0,"PLAYER_HEIGHT_INCHES":80,"SEASON":"2025-26"}\n{"PLAYER_ID":1631207,"PLAYER_NAME":"Dalen Terry","AGE":23.0,"PLAYER_HEIGHT_INCHES":78,"SEASON":"2025-26"}\n{"PLAYER_ID":1642261,"PLAYER_NAME":"Dalton Knecht","AGE":24.0,"PLAYER_HEIGHT_INCHES":78,"SEASON":"2025-26"}\n{"PLAYER_ID":1629655,"PLAYER_NAME":"Daniel Gafford","AGE":27.0,"PLAYER_HEIGHT_INCHES":82,"SEASON":"2025-26"}\n{"PLAYER_ID":1642450,"PLAYER_NAME":"Daniss Jenkins","AGE":24.0,"PLAYER_HEIGHT_INCHES":76,"SEASON":"2025-26"}\n{"PLAYER_ID":1642874,"PLAYER_NAME":"Danny Wolf","AGE":21.0,"PLAYER_HEIGHT_INCHES":83,"SEASON":"2025-26"}\n{"PLAYER_ID":203967,"PLAYER_NAME":"Dario Saric","AGE":31.0,"PLAYER_HEIGHT_INCHES":82,"SEASON":"2025-26"}\n{"PLAYER_ID":1642468,"PLAYER_NAME":"Darius Brown","AGE":26.0,"PLAYER_HEIGHT_INCHES":74,"SEASON":"2025-26"}\n{"PLAYER_ID":1629636,"PLAYER_NAME":"Darius Garland","AGE":26.0,"PLAYER_HEIGHT_INCHES":73,"SEASON":"2025-26"}\n{"PLAYER_ID":1642357,"PLAYER_NAME":"David Jones Garcia","AGE":24.0,"PLAYER_HEIGHT_INCHES":76,"SEASON":"2025-26"}\n{"PLAYER_ID":1631223,"PLAYER_NAME":"David Roddy","AGE":24.0,"PLAYER_HEIGHT_INCHES":77,"SEASON":"2025-26"}\n{"PLAYER_ID":1630558,"PLAYER_NAME":"Davion Mitchell","AGE":27.0,"PLAYER_HEIGHT_INCHES":72,"SEASON":"2025-26"}\n{"PLAYER_ID":1630549,"PLAYER_NAME":"Day\'Ron Sharpe","AGE":24.0,"PLAYER_HEIGHT_INCHES":82,"SEASON":"2025-26"}\n{"PLAYER_ID":1628368,"PLAYER_NAME":"De\'Aaron Fox","AGE":28.0,"PLAYER_HEIGHT_INCHES":75,"SEASON":"2025-26"}\n{"PLAYER_ID":1629631,"PLAYER_NAME":"De\'Andre Hunter","AGE":28.0,"PLAYER_HEIGHT_INCHES":79,"SEASON":"2025-26"}\n{"PLAYER_ID":1629001,"PLAYER_NAME":"De\'Anthony Melton","AGE":27.0,"PLAYER_HEIGHT_INCHES":74,"SEASON":"2025-26"}\n{"PLAYER_ID":201599,"PLAYER_NAME":"DeAndre Jordan","AGE":37.0,"PLAYER_HEIGHT_INCHES":83,"SEASON":"2025-26"}\n{"PLAYER_ID":201942,"PLAYER_NAME":"DeMar DeRozan","AGE":36.0,"PLAYER_HEIGHT_INCHES":78,"SEASON":"2025-26"}\n{"PLAYER_ID":1629731,"PLAYER_NAME":"Dean Wade","AGE":29.0,"PLAYER_HEIGHT_INCHES":81,"SEASON":"2025-26"}\n{"PLAYER_ID":1629028,"PLAYER_NAME":"Deandre Ayton","AGE":27.0,"PLAYER_HEIGHT_INCHES":84,"SEASON":"2025-26"}\n{"PLAYER_ID":1627749,"PLAYER_NAME":"Dejounte Murray","AGE":29.0,"PLAYER_HEIGHT_INCHES":76,"SEASON":"2025-26"}\n{"PLAYER_ID":1630166,"PLAYER_NAME":"Deni Avdija","AGE":25.0,"PLAYER_HEIGHT_INCHES":80,"SEASON":"2025-26"}\n{"PLAYER_ID":203471,"PLAYER_NAME":"Dennis Schr\\u00f6der","AGE":32.0,"PLAYER_HEIGHT_INCHES":73,"SEASON":"2025-26"}\n{"PLAYER_ID":1641726,"PLAYER_NAME":"Dereck Lively II","AGE":22.0,"PLAYER_HEIGHT_INCHES":85,"SEASON":"2025-26"}\n{"PLAYER_ID":1642852,"PLAYER_NAME":"Derik Queen","AGE":21.0,"PLAYER_HEIGHT_INCHES":81,"SEASON":"2025-26"}\n{"PLAYER_ID":1627884,"PLAYER_NAME":"Derrick Jones Jr.","AGE":29.0,"PLAYER_HEIGHT_INCHES":78,"SEASON":"2025-26"}\n{"PLAYER_ID":1628401,"PLAYER_NAME":"Derrick White","AGE":31.0,"PLAYER_HEIGHT_INCHES":76,"SEASON":"2025-26"}\n{"PLAYER_ID":1630217,"PLAYER_NAME":"Desmond Bane","AGE":27.0,"PLAYER_HEIGHT_INCHES":78,"SEASON":"2025-26"}\n{"PLAYER_ID":1626164,"PLAYER_NAME":"Devin Booker","AGE":29.0,"PLAYER_HEIGHT_INCHES":77,"SEASON":"2025-26"}\n{"PLAYER_ID":1642269,"PLAYER_NAME":"Devin Carter","AGE":23.0,"PLAYER_HEIGHT_INCHES":74,"SEASON":"2025-26"}\n{"PLAYER_ID":1630170,"PLAYER_NAME":"Devin Vassell","AGE":25.0,"PLAYER_HEIGHT_INCHES":77,"SEASON":"2025-26"}\n{"PLAYER_ID":1628415,"PLAYER_NAME":"Dillon Brooks","AGE":30.0,"PLAYER_HEIGHT_INCHES":79,"SEASON":"2025-26"}\n{"PLAYER_ID":1641794,"PLAYER_NAME":"Dillon Jones","AGE":24.0,"PLAYER_HEIGHT_INCHES":77,"SEASON":"2025-26"}\n{"PLAYER_ID":1627734,"PLAYER_NAME":"Domantas Sabonis","AGE":29.0,"PLAYER_HEIGHT_INCHES":82,"SEASON":"2025-26"}\n{"PLAYER_ID":1631230,"PLAYER_NAME":"Dominick Barlow","AGE":22.0,"PLAYER_HEIGHT_INCHES":81,"SEASON":"2025-26"}\n{"PLAYER_ID":1642270,"PLAYER_NAME":"Donovan Clingan","AGE":22.0,"PLAYER_HEIGHT_INCHES":86,"SEASON":"2025-26"}\n{"PLAYER_ID":1628378,"PLAYER_NAME":"Donovan Mitchell","AGE":29.0,"PLAYER_HEIGHT_INCHES":74,"SEASON":"2025-26"}\n{"PLAYER_ID":1628978,"PLAYER_NAME":"Donte DiVincenzo","AGE":29.0,"PLAYER_HEIGHT_INCHES":76,"SEASON":"2025-26"}\n{"PLAYER_ID":1627827,"PLAYER_NAME":"Dorian Finney-Smith","AGE":32.0,"PLAYER_HEIGHT_INCHES":79,"SEASON":"2025-26"}\n{"PLAYER_ID":203926,"PLAYER_NAME":"Doug McDermott","AGE":34.0,"PLAYER_HEIGHT_INCHES":79,"SEASON":"2025-26"}\n{"PLAYER_ID":1642962,"PLAYER_NAME":"Drake Powell","AGE":20.0,"PLAYER_HEIGHT_INCHES":77,"SEASON":"2025-26"}\n{"PLAYER_ID":203110,"PLAYER_NAME":"Draymond Green","AGE":36.0,"PLAYER_HEIGHT_INCHES":78,"SEASON":"2025-26"}\n{"PLAYER_ID":1629234,"PLAYER_NAME":"Drew Eubanks","AGE":29.0,"PLAYER_HEIGHT_INCHES":82,"SEASON":"2025-26"}\n{"PLAYER_ID":1641809,"PLAYER_NAME":"Drew Peterson","AGE":26.0,"PLAYER_HEIGHT_INCHES":80,"SEASON":"2025-26"}\n{"PLAYER_ID":1631166,"PLAYER_NAME":"Drew Timme","AGE":25.0,"PLAYER_HEIGHT_INCHES":81,"SEASON":"2025-26"}\n{"PLAYER_ID":1630696,"PLAYER_NAME":"Dru Smith","AGE":28.0,"PLAYER_HEIGHT_INCHES":74,"SEASON":"2025-26"}\n{"PLAYER_ID":1629130,"PLAYER_NAME":"Duncan Robinson","AGE":31.0,"PLAYER_HEIGHT_INCHES":79,"SEASON":"2025-26"}\n{"PLAYER_ID":1641871,"PLAYER_NAME":"Duop Reath","AGE":29.0,"PLAYER_HEIGHT_INCHES":81,"SEASON":"2025-26"}\n{"PLAYER_ID":203939,"PLAYER_NAME":"Dwight Powell","AGE":34.0,"PLAYER_HEIGHT_INCHES":82,"SEASON":"2025-26"}\n{"PLAYER_ID":1642928,"PLAYER_NAME":"Dylan Cardwell","AGE":24.0,"PLAYER_HEIGHT_INCHES":82,"SEASON":"2025-26"}\n{"PLAYER_ID":1642844,"PLAYER_NAME":"Dylan Harper","AGE":20.0,"PLAYER_HEIGHT_INCHES":77,"SEASON":"2025-26"}\n{"PLAYER_ID":1630700,"PLAYER_NAME":"Dyson Daniels","AGE":22.0,"PLAYER_HEIGHT_INCHES":79,"SEASON":"2025-26"}\n{"PLAYER_ID":1630604,"PLAYER_NAME":"E.J. Liddell","AGE":25.0,"PLAYER_HEIGHT_INCHES":78,"SEASON":"2025-26"}\n{"PLAYER_ID":1642856,"PLAYER_NAME":"Egor D\\u00ebmin","AGE":20.0,"PLAYER_HEIGHT_INCHES":80,"SEASON":"2025-26"}\n{"PLAYER_ID":1641989,"PLAYER_NAME":"Elijah Harkless","AGE":26.0,"PLAYER_HEIGHT_INCHES":75,"SEASON":"2025-26"}\n{"PLAYER_ID":1641801,"PLAYER_NAME":"Emanuel Miller","AGE":25.0,"PLAYER_HEIGHT_INCHES":77,"SEASON":"2025-26"}\n{"PLAYER_ID":1642402,"PLAYER_NAME":"Enrique Freeman","AGE":25.0,"PLAYER_HEIGHT_INCHES":81,"SEASON":"2025-26"}\n{"PLAYER_ID":201569,"PLAYER_NAME":"Eric Gordon","AGE":37.0,"PLAYER_HEIGHT_INCHES":75,"SEASON":"2025-26"}\n{"PLAYER_ID":1630679,"PLAYER_NAME":"Ethan Thompson","AGE":26.0,"PLAYER_HEIGHT_INCHES":76,"SEASON":"2025-26"}\n{"PLAYER_ID":1630596,"PLAYER_NAME":"Evan Mobley","AGE":24.0,"PLAYER_HEIGHT_INCHES":83,"SEASON":"2025-26"}\n{"PLAYER_ID":1630532,"PLAYER_NAME":"Franz Wagner","AGE":24.0,"PLAYER_HEIGHT_INCHES":82,"SEASON":"2025-26"}\n{"PLAYER_ID":1641713,"PLAYER_NAME":"GG Jackson","AGE":21.0,"PLAYER_HEIGHT_INCHES":81,"SEASON":"2025-26"}\n{"PLAYER_ID":1629216,"PLAYER_NAME":"Gabe Vincent","AGE":29.0,"PLAYER_HEIGHT_INCHES":74,"SEASON":"2025-26"}\n{"PLAYER_ID":202066,"PLAYER_NAME":"Garrett Temple","AGE":39.0,"PLAYER_HEIGHT_INCHES":77,"SEASON":"2025-26"}\n{"PLAYER_ID":1629726,"PLAYER_NAME":"Garrison Mathews","AGE":29.0,"PLAYER_HEIGHT_INCHES":77,"SEASON":"2025-26"}\n{"PLAYER_ID":203914,"PLAYER_NAME":"Gary Harris","AGE":31.0,"PLAYER_HEIGHT_INCHES":76,"SEASON":"2025-26"}\n{"PLAYER_ID":1627780,"PLAYER_NAME":"Gary Payton II","AGE":33.0,"PLAYER_HEIGHT_INCHES":74,"SEASON":"2025-26"}\n{"PLAYER_ID":1629018,"PLAYER_NAME":"Gary Trent Jr.","AGE":27.0,"PLAYER_HEIGHT_INCHES":77,"SEASON":"2025-26"}\n{"PLAYER_ID":203507,"PLAYER_NAME":"Giannis Antetokounmpo","AGE":31.0,"PLAYER_HEIGHT_INCHES":83,"SEASON":"2025-26"}\n{"PLAYER_ID":1629048,"PLAYER_NAME":"Goga Bitadze","AGE":26.0,"PLAYER_HEIGHT_INCHES":83,"SEASON":"2025-26"}\n{"PLAYER_ID":1641711,"PLAYER_NAME":"Gradey Dick","AGE":22.0,"PLAYER_HEIGHT_INCHES":79,"SEASON":"2025-26"}\n{"PLAYER_ID":1641761,"PLAYER_NAME":"Grant Nelson","AGE":23.0,"PLAYER_HEIGHT_INCHES":84,"SEASON":"2025-26"}\n{"PLAYER_ID":1629684,"PLAYER_NAME":"Grant Williams","AGE":27.0,"PLAYER_HEIGHT_INCHES":79,"SEASON":"2025-26"}\n{"PLAYER_ID":1628960,"PLAYER_NAME":"Grayson Allen","AGE":30.0,"PLAYER_HEIGHT_INCHES":75,"SEASON":"2025-26"}\n{"PLAYER_ID":1627824,"PLAYER_NAME":"Guerschon Yabusele","AGE":30.0,"PLAYER_HEIGHT_INCHES":79,"SEASON":"2025-26"}\n{"PLAYER_ID":1630611,"PLAYER_NAME":"Gui Santos","AGE":23.0,"PLAYER_HEIGHT_INCHES":79,"SEASON":"2025-26"}\n{"PLAYER_ID":2030